### ISSUE TITLE
How to change the base point G in the Bitcoin module for generating public keys?

### ISSUE THREAD

**Issue by amiwrcd** [1200wd/bitcoinlib#102]
I want to change in the code to a base point G to generate public keys?

I only start programming on Python 3 and do not understand the modules
How can I change this code?

**Comment by mccwdev** [comment]
The secp256k1 parameters are defined in bitcoinlib/config/secp256k1.py. You could change these parameters but I'm not sure what it will mean for security or functioning of the library.
