### ISSUE TITLE
Could not parse rfc1738 URL from string

### ISSUE THREAD

**Issue by kazemi56** [1200wd/bitcoinlib#106]
```
from bitcoinlib.wallets import HDWallet
w = HDWallet.create('Wallet1')
```
I am receiving:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\
bitcoinlib\wallets.py", line 1170, in create
    hdpm = cls._create(name, key, owner=owner, network=network, account_id=accou
nt_id, purpose=purpose,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\
bitcoinlib\wallets.py", line 945, in _create
    session = DbInit(db_uri=db_uri).session
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\
bitcoinlib\db.py", line 55, in __init__
    self.engine = create_engine(db_uri, isolation_level='READ UNCOMMITTED')
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\
sqlalchemy\engine\__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\
sqlalchemy\engine\strategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\
sqlalchemy\engine\url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\
sqlalchemy\engine\url.py", line 290, in _parse_rfc1738_args
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'C:\Users\
User\.bitcoinlib/database\bitcoinlib.sqlite'
```
can somebody help me?
Thank you

**Comment by JHJohny** [comment]
The problem will be with string itself - 'C:\Users\User\.bitcoinlib**/**database\bitcoinlib.sqlite'
Take a look at punctuation. 
As I am not using windows, I can't try it by myself. 
Does path exist like that? With opposite slash? 
Trying figure out what is passing path this way - the program or OS.

**Comment by kazemi56** [comment]
> The problem will be with string itself - C:\Users\User.bitcoinlib`/`database\bitcoinlib.sqlite
> Take a look at punctuation.
> As I am not using windows, I can't try it by myself.
> Does path exist like that? With opposite slash?
> Trying figure out what is passing path this way - the program or OS.

Thank You
The Problem is solved.

I changed "database_dir=.bitcoinlib/database" to "database_dir=.bitcoinlib\database" in config.ini
and in db.py  I added this line:
`db_uri = 'sqlite:///' + db_uri.replace('\\','\\\\')`

https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#module-sqlalchemy.dialects.sqlite.pysqlite

**Comment by mccwdev** [comment]
Using pathlib now to avoid this kind of issues
