### ISSUE TITLE
Multisig wallet addresses don't match up

### ISSUE THREAD

**Issue by deaddarkdev** [1200wd/bitcoinlib#109]
I am developing an application which will create a hosted multisig wallet and allow users to use the Electrum client to manage their keys and signatures.  However, I can't get Electrum to produce the same addresses and bitcoinlib.  I've walked through the code and I suspect the lib is using the wrong key to create the transaction.  

Steps

- Start Electrum Version 3.3.8 on testnet
`electrum --testnet `

- Create a new wallet - Choose Multi-signature
- Select 2 cosigners & Require 2 signatures
- Select "I already have a seed"

- Enter seed `during shoot page code wall kiwi easy unhappy december noise wool honey`
- Copy public key.  Should be `Vpub5fR49HdWfbfr74Amzhfzn3hidq1PWqoVznMRtXBN8MGUQe6UtUwX5JJB9dvRnXFsDe217mwHxtTz6tCkAHWzFJizMb5r17arjLohxiPdT1y`
- Create HDKey from the public key 

```
otherkey = HDKey(
'Vpub5fR49HdWfbfr74Amzhfzn3hidq1PWqoVznMRtXBN8MGUQe6UtUwX5JJB9dvRnXFsDe217mwHxtTz6tCkAHWzFJizMb5r17arjLohxiPdT1y',
    key_type='single',
    )
```

- Create personal private/public key pair
```
  mykey = HDKey('vprv9DMUxX4ShgxMLjXDXiZJCKtKoyPdR9e9o7onfgbXRAHd5k9jHZUpHFKFbpkakkUPPRWGDr5NVkykbJyvyzDFrZ8HhjggeAsJcj3dEZJoeiD',
  network=NETWORK,
  witness_type='segwit'
  )
```

- Create Multisig HD wallet
```
klist = [mykey, otherkey]
wallet1 = HDWallet.create_multisig('multisig_1of2_cosigner1', sigs_required=2, keys=klist,
                                   network=NETWORK, db_uri=test_database, witness_type='segwit)
```

- Verify wallet info
```
wallet1.info()
=== Wallet1 Info ===
=== WALLET ===
 ID                             1
 Name                           multisig_1of2_cosigner1
 Owner                          
 Scheme                         bip32
 Multisig                       True
 Multisig Wallet IDs            2, 3
 Cosigner ID                    0
 Witness type                   segwit
 Main network                   testnet
 Latest update                  None

= Multisig Public Master Keys =
    0   1 Vpub5m8tTWZiU72EQAbRUswWHsWoNWe1MTQcZ57G56r2M63P9omG7dV2zfqpRMSByModsAqCpxmovpDVWrK8AgUVBc8cKiB9w6RHHvsn2HDdnjj bip32  main     *
    1   8 Vpub5fR49HdWfbfr74Amzhfzn3hidq1PWqoVznMRtXBN8MGUQe6UtUwX5JJB9dvRnXFsDe217mwHxtTz6tCkAHWzFJizMb5r17arjLohxiPdT1y single cosigner 
For main keys a private master key is available in this wallet to sign transactions. * cosigner key for this wallet

- NETWORK: testnet -
- - Keys

- - Transactions Account 0 (0)

= Balance Totals (includes unconfirmed) =


```
- Import Public Master Key back into Electrum by selecting "Enter the cosigner key"
and pasting  
`Vpub5m8tTWZiU72EQAbRUswWHsWoNWe1MTQcZ57G56r2M63P9omG7dV2zfqpRMSByModsAqCpxmovpDVWrK8AgUVBc8cKiB9w6RHHvsn2HDdnjj`
into the ui

- Skip password

- Verify Electrum wallet  Wallet->Information
Should be 2 keys there:
```
cosigner 1: Vpub5fR49HdWfbfr74Amzhfzn3hidq1PWqoVznMRtXBN8MGUQe6UtUwX5JJB9dvRnXFsDe217mwHxtTz6tCkAHWzFJizMb5r17arjLohxiPdT1y
cosigner 2: Vpub5m8tTWZiU72EQAbRUswWHsWoNWe1MTQcZ57G56r2M63P9omG7dV2zfqpRMSByModsAqCpxmovpDVWrK8AgUVBc8cKiB9w6RHHvsn2HDdnjj
```

- Create receive address in Electrum with menu "Receive"
Address created is` tb1qy936w6lhanejk6kt0jxya0x7yz25mxsewrws2gjyx2hupqvx5a8skks4v8`

- Create receive address with HDWallet
```
nk1 = wallet1.get_key()
print(nk1.address)
```

Address created is `tb1qz59drk8xrla72zp294grr8gguxqvrtgyjwr6rnhdkv6emgh2txkqjw7m8s`

Expected results: 
Addresses should match every generation 

Actual results:
Addresses never match and wallets never share keys.

**Comment by mccwdev** [comment]
By default Electrum uses slightly different Mnemonic seeds, it add's a version number.

When you enter a seed in Electrum, you can click options and select 'BIP39 seed'.
This way you use the same standard in BitcoinLib and Electrum and generate identical addresses.

**Comment by deaddarkdev** [comment]
I'm only using the seed to generate the public key in Electrum then using that key in BitcoinLib.  Both wallets show exactly the same public keys.  I've even loaded both wallets with identical key pairs.  But I still can't generate the same address.  Can you reproduce?  I'm going to test with Armory next.

**Comment by deaddarkdev** [comment]
I have set options to BIP39 seed.  But I still can't generate addresses that match.  Both wallets have the same public keys.
```
=== Wallet1 Info ===
=== WALLET ===
 ID                             1
 Name                           multisig_1of2_cosigner1
 Owner                          
 Scheme                         bip32
 Multisig                       True
 Multisig Wallet IDs            2, 3
 Cosigner ID                    1
 Witness type                   segwit
 Main network                   testnet
 Latest update                  None

= Multisig Public Master Keys =
    0   1 Vpub5nBJ4d6EtB48tiA9qfJy5PwTKhtfPMguRjYNwsqNuF276QJzc6dr235UDZit1ZCWxeRMfXfyU38aYutnUj5mWnxyS7XnTL6hWzCDv3bEMkC single cosigner 
    1   2 Vpub5nXwWW7YEzQuhueZqNV8akKFoAxvg5RqTRSoV6BXVFR1v22h5nkHgLyUtcTmN8VBuu2t3wHZ8Rn3oW6ztyR9GXvHgGQKnHhY6rB8RgcNT9v bip32  main     *
For main keys a private master key is available in this wallet to sign transactions. * cosigner key for this wallet

- NETWORK: testnet -
- - Keys

- - Transactions Account 0 (0)

= Balance Totals (includes unconfirmed) =


Deposit testnet bitcoin to this address to create transaction:  tb1qdp3cjt28ttcvh48a6k2v9snzjcwl48gersq5fcxdfclt6cckmeescv4c00
```

Electrum
```
during shoot page code wall kiwi easy unhappy december noise wool honey
p2wish
m/48'/1'/0'/2'

Vpub5nBJ4d6EtB48tiA9qfJy5PwTKhtfPMguRjYNwsqNuF276QJzc6dr235UDZit1ZCWxeRMfXfyU38aYutnUj5mWnxyS7XnTL6hWzCDv3bEMkC

address: tb1qnlaf3yatdyupphpew4m6ldfec02h54pe3pp0drswrs8apag04css9zufcu
```

**Comment by deaddarkdev** [comment]
I was importing the electrum key as a type "single_key" instead of "bop32".  This was causing the issue. Thanks for the tip!
