### ISSUE TITLE
Incorrect Bitcoin Account Balance?

### ISSUE THREAD

**Issue by famecastle** [1200wd/bitcoinlib#112]
I'm using a default SQLite database on the Bitcoin Testnet with a `HDWallet`.

I'm entirely working on the account with id 0. For my users, however, I created individual keys using `wallet.new_key(account_id=0)` .

As long as I'm sending money to the same key (no matter how often), the balance total of account 1 updates and increases accordingly.

However once I create a new key on account one and send money to that freshly generated key, the account balance is being reset/overriden exclusively by the new key's balance.

I've posted the terminal output below. You can see the three transactions with the last one going to a new key address. The amount of that new key transaction is then shown as the total account balance below. But shouldn't it be the sum of all three transactions to that account?

What's wrong here?

```
>>> wallet.info()
=== WALLET ===
 ID                             7
 Name                           Test_Wallet_6
 Owner                          
 Scheme                         bip32
 Multisig                       False
 Witness type                   legacy
 Main network                   testnet
 Latest update                  None

= Wallet Master Key =
 ID                             1668
 Private                        True
 Depth                          0

- NETWORK: testnet -
- - Keys
 1673 m/44'/1'/0'/0/0              mjoEN6m3fWYwGyU3f5wo2TkCV6jeHc8B5o            address index 0                     0.00000000 TBTC
 1676 m/44'/1'/1'/0/0              mfdnhyFMz8ePk1dFFsnrh7xipYDgmEh5RZ            address index 0                     0.00000000 TBTC
 1678 m/44'/1'/1'/1/0              mzjpLV62aM8Vr3LvXRBku5triUp914Q7hu            address index 0                     0.00000000 TBTC
 1679 m/44'/1'/0'/0/1              mmpV2oQbV6YqD9d865btQmPUe4RsUG6VXs            address index 1                     0.00000000 TBTC
 1680 m/44'/1'/0'/0/2              n3wXe1yQdzDaDu2QkWuG7QLuAi6fsVuY5p            address index 2                     0.00000000 TBTC

- - Transactions Account 0 (3)
7a91256af3537e26346aa7ae64451de8bba8c7d9e93320e30d2d42b08eb10e1a   mmpV2oQbV6YqD9d865btQmPUe4RsUG6VXs        0        200000   
b924605614093806c78ba8eee5e7dd8fbad320824399d7bcf01049336f85df53   mmpV2oQbV6YqD9d865btQmPUe4RsUG6VXs        0        100000   
72606e07e9131112bb9f867dda9913a939cc1b3c8ccf46799f7987d798c54047   n3wXe1yQdzDaDu2QkWuG7QLuAi6fsVuY5p        0        400000   

- - Transactions Account 1 (0)

= Balance Totals (includes unconfirmed) =
testnet              (Account 0)               0.00400000 TBTC
```

Thanks for your efforts.

**Comment by famecastle** [comment]
Just figured this out myself! It's worth pointing out that using `wallet.utxos_update(account_id=..., key_id=...)` also implies `rescan_all=True` . This parameter removes all previous UTXOs and adds those newly updated to the db again. But if you only update one single key (the most recent key in my specific case), and all other data is being deleted anyway, you will only have data for that particular key in your database which results in the total balance only detecting your specific key.

I think this behavior should be changed so that utxos_update detects whether you have specified a key_id and then implies `rescan_all=False`.

**Comment by mccwdev** [comment]
Fixed in https://github.com/1200wd/bitcoinlib/tree/fix-issue-112
