### ISSUE TITLE
(sqlite3.IntegrityError) constraint constraint_script_types_allowed failed 

### ISSUE THREAD

**Issue by kjandrew90** [1200wd/bitcoinlib#115]
I'm using bitcoinlib==0.4.3 whith python 2.7.5 and I've create a new wallet with custom db path. I try to send some bytcoin to public address of the wallet, i the blockchain i see the transaction but in the software when I try to do w.scan() I receive the error:
`sqllalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) constraint constraint_script_types_allowed failed [SQL: u'INSERT INTO transaction_inputs (transaction_id, index_n, key_id, prev_hash, output_n, script, script_type, sequence, value, double_spend) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (1, 0, None, '5aad7ba83923r45bcd5765s6bb34e25f95de699bb7f9f245279713c32ae542', 6, '220020748fbdbd734e14b0320f508405a6df58a281f1ca01a745adaa56bf64ace', 'p2sh_p2wsh', None, 1712980, 0)] (Background on this error at: http://sqlalche.me/e/gkpj)`
Someone can help me? Thank you

**Comment by mccwdev** [comment]
Hi, Could you try to upgrade to the latest version of bitcoinlib? Since you are using a 2018 version, this will probably solve your problem.
