### ISSUE TITLE
Rollback on Database Errors [Important Enhancement]

### ISSUE THREAD

**Issue by famecastle** [1200wd/bitcoinlib#116]
So it could always happen that the connection to a database breaks (for example to MySQL or PostgreSQL). While reconnection is possible due to the use of connection pools (the default), a failed transaction causes all further transactions to fail as well (SQLAlchemy tells you that you need to rollback the failed transaction first). This makes this library practically unusable for productive use unfortunately!

Hence, every failed transaction should be rolled back when an error occurs (simple try-except stuff). I hope this can be done easily.

Thanks!

------------------------------------

Out of context: You seem to have much knowledge of ORM DBs. I decided to use Postgres but it gives me so many connection errors - even though I have pgbouncer in the middle. Should I go with MySQL/MariaDB instead? Which one is better? Also, how can I ensure that this library works with let's say 1000 concurrent wallet actions (sending transactions, updating wallet addresses) regarding database connections? I have multiple processes accessing the wallet at the same time.

**Comment by mccwdev** [comment]
I agree, roll back on error is definitely something we need to implement on every database transaction before this library is ready for large scale production use.

Unfortunately I am not a database expert @Moliholy implemented the MySQL and PostgreSQL connections. Maybe he has some advice on which database is best for you. Initially this library is setup with SQLite only.

**Comment by Moliholy** [comment]
Hello!

> Hence, every failed transaction should be rolled back when an error occurs (simple try-except stuff). I hope this can be done easily.

I totally agree. This could be done by simply wrapping the `session.commit()` calls in the code with a try/except block. It shouldn't be hard.

> Should I go with MySQL/MariaDB instead?

Both are decent database options. I personally prefer (and I'm using in production as well) PostgreSQL, but there is no special recommendation I could make. I am hosting separate databases in separate machines for each crypto currency. Concretely, Bitcoin usually has much more traffic and others, so it's isolated in a more powerful machine, while the rest are all together in a smaller machine, but each one in a different database. This way if for whatever reason I one day have to migrate, say Litecoin, it's much easier and cleaner to do it.
