### ISSUE TITLE
Bitcoinlib spamming connections to MySQL server

### ISSUE THREAD

**Issue by famecastle** [1200wd/bitcoinlib#117]
I have a simple loop. A supervisor program called supervisord runs my program four times in parallel.

This is the code:

```python
from pymongo import MongoClient, ReturnDocument
from bson.objectid import ObjectId
from datetime import datetime, timedelta
from bitcoinlib.wallets import HDWallet
from decimal import Decimal, getcontext
from aioify import aioify
from redis import StrictRedis
import logging
import asyncio
import config
import time
import json
import math
import sys

[...]
wallet = HDWallet(config.master_wallet, db_uri=config.dburi) # a normal MySQL URI

def observe_wallets(log_function, on_event):
    getcontext().prec = 6 # Decimal() auto-rounding precision
    time.sleep(2)
    retry_errors = 0
    while True:
        try:
            [...]
            wallet.utxos_update(account_id=account["account_id"], key_id=account["key_id"], rescan_all=False)
            transactions = wallet.transactions(include_new=True, account_id=account["account_id"], key_id=account["key_id"])
            for transaction in transactions:
                if transaction.outputs[0].address not in wallet.addresslist(account_id=account["account_id"], key_id=account["key_id"]):
                    continue
                btc_amount = round(Decimal(transaction.outputs[0].value) * Decimal(config.satoshi_in_btc), 5)
                snacs = math.floor(Decimal(btc_amount) / Decimal([...]))
                if transaction.confirmations < config.transaction_confirmation_threshold and transaction.hash not in account["unconfirmed_transactions"]:
                    [...]
                elif transaction.confirmations >= config.transaction_confirmation_threshold and transaction.hash not in account["confirmed_transactions"]:
                    [...]
            if len(transactions) >= config.max_transactions_per_address:
                account["archived"] = True
            retry_errors = 0
[...]

if __name__ == "__main__":
   observe_wallets([...], [...])
```

I've added all the bitcoinlib-relevant parts. As you can see I'm not recreating the HDWallet object anywhere.

Why is, in each iteration, Bitcoinlib creating and holding open new connections to my MySQL server? This makes it unusable unfortunately. It seems like most of the connections only have one action ever performed called "rollback". I've attached a screenshot of the MySQL Workbench a few seconds after I started my program. The gradually increase - I even had them around 200!

Please help now! It's urgent.
Thanks in advance!

-------------------------------

![image](https://user-images.githubusercontent.com/11258821/78823915-d070ad00-79dd-11ea-8286-0095f11c7b59.png)

**Comment by famecastle** [comment]
I found out that this happens in version 0.4.14 - downgrading to 0.4.12 fixed it. So something is wrong with your recent update.

**Comment by mccwdev** [comment]
Thanks for the detailed example, I will look into it.

**Comment by mccwdev** [comment]
I found a problem in the new caching part of the library creating a database commit for every transaction input and output. I assume this is the origin of this problem as well.
It has been fixed in https://github.com/1200wd/bitcoinlib/commit/f74b24dc9275aa1bc6ee283c95e8687e54ed9a0e and will be merged to the master branch in the next few weeks.
