### ISSUE TITLE
Feature request: contact list or k/v store

### ISSUE THREAD

**Issue by shyal** [1200wd/bitcoinlib#121]
Hi all,

I'm building an application that uses this great lib, and would like implement a contact list. Looks like i'll create a database alongside yours.. and was wondering whether it would be worth investigating having a user defined k/v store via this lib.

Thoughts?

Happy to do it myself if you think it's reasonable. Might be a dumb idea.

Thanks

**Comment by mccwdev** [comment]
Yes this might be a good idea, but probably will fit more in an application based on this library then included in the library itself.  Because I think it's quite use-case specific, but that's just my opinion...

**Comment by shyal** [comment]
Absolutely right. However a method to store user data is quite typical, whatever that user data may be. Even a table for storing string data means i could store contacts with <name>_contact keys, and json docs. It's dirty but works very well for small applications, scripts etc. and caters for many use cases.
