### ISSUE TITLE
Wrong config.ini sample file

### ISSUE THREAD

**Issue by ldubravica** [1200wd/bitcoinlib#122]
According to the bitcoinlib/data/config.ini file, variable **log_file** should be located in the _logs_ section

`[logs]`
`enable_bitcoinlib_logging=True`
`log_file=~bitcoinlib.log`
`loglevel=WARNING`

But after studying your code, I saw that it is actually being fetched from _locations_ section in bitcoinlib/config/config.py

`BCL_LOG_FILE = Path(BCL_DATA_DIR, config_get('locations', 'log_file', fallback='bitcoinlib.log'))`

**Comment by mccwdev** [comment]
fixed
