### ISSUE TITLE
Automatically decrement fee from amount when sending

### ISSUE THREAD

**Issue by ealmuina** [1200wd/bitcoinlib#130]
It would be nice to be able to indicate through a boolean parameter when the sender wants the fee to be decremented directly from the amount to be sent.

Sometimes you want to transfer all your funds from one wallet to another, and being able to just indicate the amount without having to worry about the fees would be awesome.

**Comment by mccwdev** [comment]
You could transfer all funds from one wallet to another by using the wallets sweep method.

In the send, send_to or sweep method you can specify the fee amount as well.

**Comment by ealmuina** [comment]
Yeah, but it's nice to have the library automatically calculate the fee for you, and deduct it from the amount to transfer if you want to.
