### ISSUE TITLE
[Q] How to send funds?

### ISSUE THREAD

**Issue by wildprint** [1200wd/bitcoinlib#132]
I created wallet, then I got address `w.get_key().address`, then I send some funds to this address. I left python, then I type `clw ... -r` and got another address. So I can't send funds because balance is 0 (but previous address has some ltc). 
What wrong I did?
`w.adddresslist()` contains previous address and current but balance is 0
How can I send funds?

**Comment by mccwdev** [comment]
First all transactions and UTXO's must be known by the wallet:
`$ clw <wallet-id> -u`

or from python:
 `>>> w.scan()`

To create a transaction from commandline use:
 `$ clw <wallet-id> --create-transaction <address> <amount>`
to push it add -p
 `$ clw <wallet-id> --create-transaction <address> <amount> -p`

See https://bitcoinlib.readthedocs.io/en/latest/_static/manuals.command-line-wallet.html#send-funds-create-transaction

Or to send funds from Python use 
 `>>> w.send_to(<address>, <amount>)`
