### ISSUE TITLE
sending segwit transaction

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [1200wd/bitcoinlib#136]
Hi. I'm trying to push a segwit transaction to the bitcoin testnet network. the main part of my code is as below:
`input = Input(prev_hash=prev_hash, output_n=output_n,keys=key.public(), network='testnet' ,witness_type="segwit" )`
`output = Output(amount, address=outputAddress, network='testnet'))`
`t = Transaction(input, output, network='testnet' , witness_type="segwit" , fee = fee)`
`t.sign(key.private_byte)`
`t.verify()`

when I run this code I get following error raised from line `t.sign(key.private_byte)` :

"bitcoinlib.transactions.TransactionError: Need value of input 0 to create a transaction signature, value can not be 0"
and when I delete this line the result of `t.verify()` becomes False.
I wonder that did I miss something in creating the transaction? I appreciate any help

**Comment by mccwdev** [comment]
The value's of the transaction inputs are needed to sign and verify a transaction. 

So for example:
 input = Input(prev_hash=prev_hash, output_n=output_n,keys=key.public(), network='testnet' ,witness_type="segwit", value=input_value)
