### ISSUE TITLE
non-mandatory-script-verify-flag

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [1200wd/bitcoinlib#137]
I create a transaction using the following code and when I push this transaction to the network I get this error:
"sendrawtransaction RPC error: {"code":-26,"message":"non-mandatory-script-verify-flag (Non-canonical signature: S value is unnecessarily high)"}"

my code is as below :
```
input = Input(prev_hash=prev_hash, output_n=output_n,keys=key.public(), network='testnet' ,witness_type="segwit" , value = value )
output = Output(amount, address=outputAddress, network='testnet'))
t = Transaction(input, output, network='testnet' , witness_type="segwit" , fee = fee , version = 2)
t.sign(key.private_byte)
t.verify()
s = t.inputs[0].signatures[0].s
print("s: ", s)
print("max s:", int(secp256k1_n / 2))
print("canonical? ", bool(int(s) < secp256k1_n / 2))
```

and I get the following output :
s: 4433750427723256683445658442641718727065179203509893270619600250655989546140
max s: 57896044618658097711785492504343953926634992332820282019728792003956564819968
canonical? True

I tested it with version 1 transactions and legacy transactions too. the only situation that I don't get this error is when I use `version= 1` and `witness_type="legacy"`

**Comment by mccwdev** [comment]
Thanks for your report, I will try to reproduce. Can you confirm you use the latest version of the library?

**Comment by Mahsa-Bastankhah** [comment]
yes I use the version 0.4.19

**Comment by mccwdev** [comment]
Hi, I couldn't reproduce the error. 

I have checked with several witness types and transactions version, but everything seems to work. You can find my code at https://gist.github.com/mccwdev/5c1e864781f885e1397d59b081b133b6. 

So I assume some problems with your inputs values. Let me know if you're able to fix, and don't hesitate to contact me again.

**Comment by Mahsa-Bastankhah** [comment]
Hi. thanks for your reply. I charged the 'k1' address with some test bitcoin and ran your code. it ran without problem and I got the hash of transaction. but if I replace the line `srv.sendrawtransaction(t.raw_hex())` with `print(t.raw_hex(witness_type=witness_type))` and I copy the raw transaction in  [https://blockstream.info/testnet/tx/push] or any other provider that pushes the transaction (except Blockcypher) I will get the non-mandatory-script-verify-flag error. and when I push the transaction through Blockcypher the transaction usually doesn't get confirmed and the number of transaction pools containing this transaction is very low even if the transaction fee is high. so I guess something is wrong with this transaction that causes some of bitcoin nodes not to verify it and as a result, the transaction gets confirmed very late or doesn't get confirmed at all. but I'm not sure about my guess.

**Comment by mccwdev** [comment]
Thanks for your detailed description. And yes Blockcypher accepts incorrect/non-standard transactions and tries to push them to the network, which can be quite unhandy sometimes.

The raw hex you provided indeed has a high s-value so it's not a valid transaction. I'm not sure how you where able to generate it however. I have tried with a script with 100 generations and always t.raw_hex() and t.raw_hex(witness_type=witness_type) produced the same result and where valid transactions. 

I assume somewhere the wrong witness_type is used somewhere which causes the problem. But normally you shouldn't use the witness_type attribute when creating a raw transaction, it is used to create transaction signature ID's for segwit transactions.

**Comment by Mahsa-Bastankhah** [comment]
I ran the following code several times and I got a weird result.
`network = 'testnet'`
`witness_type = 'segwit'`
`version = 2`
`mk = HDKey(prv_wif, witness_type=witness_type)`
`k1 = mk`
`srv = Service(network='testnet')`
`utxos = srv.getutxos(k1.address())`
`if not utxos:
         sys.exit()`
`indx = 0`
`prev_txid = utxos[indx]['tx_hash']`
`output_n = utxos[indx]['output_n']`
`value = utxos[indx]['value']`
`input = Input(prev_hash=prev_txid, output_n=output_n, keys=k1.public(), network='testnet', value=value,
              witness_type=witness_type)`
`output = Output(value - fee, address=addr_to, network='testnet')`
`t = Transaction([input], [output], network='testnet', witness_type=witness_type, version=version)`
`t.sign(k1)`
`t.verify()`
`t.info()`
`s = t.inputs[0].signatures[0].s`
`print("s: ", s)`
`print("max s:", int(secp256k1_n / 2))`
`print("first test canonical? ", bool(int(s) < secp256k1_n / 2))`
`print(t.raw_hex())`
`rawtx = t.raw_hex()`
`t = Transaction.import_raw(rawtx , network='testnet')`
`s = t.inputs[0].signatures[0].s`
`print("s: ", s)`
`print("max s:", int(secp256k1_n / 2))`
`print("second test canonical? ", bool(int(s) < secp256k1_n / 2))`

note that I have checked the value of s two times. in second test I've imported used the result of imported raw transaction. most of the times result of both of `print("first test canonical? ", bool(int(s) < secp256k1_n / 2))` and `print("second test canonical? ", bool(int(s) < secp256k1_n / 2))` are true and I can push the transaction in blockstream successfully. 
but sometimes the second test gives `False` while the first one gives `Tru` and the s value they show are different . I copied the result of one of these run at following :

s:  47095836420974790820848156340561475294965878188892668100501839099814769694281
max s: 57896044618658097711785492504343953926634992332820282019728792003956564819968
canonical?  True
s:  68696252816341404602722828668126432557871686090182236282103324041703391800056
max s: 57896044618658097711785492504343953926634992332820282019728792003956564819968
canonical?  False

and if you push this raw transaction in Blockstream you will definitely get the non-mandatory error. so to sum up, I can tell that the output of the above code is a correct raw transaction most of the times but sometimes it has an invalid s value when we import it and also this transaction can't be pushed to the network. I can't find where the problem is because it seems to be totally random.

**Comment by mccwdev** [comment]
Tried your code with different keys, utxos and many iterations, but no errors.

Seems the problems lies in the import_transaction method. The s value should be same, because the signatures are in the unlocking script of the transaction input. If you serialize the transaction again after import_transaction you should get exactly the same transaction. So maybe you could add a test for this and see if you could trace the error.
 rawtx = t.raw_hex()
 t2 = Transaction.import_raw(rawtx, network='testnet')
 assert(rawtx == t2.raw_hex())

Maybe for some reason the import_transaction which uses transaction_deserialize doesn't recognise the imported transaction as a segwit transaction.

**Comment by Mahsa-Bastankhah** [comment]
the raw transaction is the same and assert(rawtx == t2.raw_hex()) always passes but the s value is totally different in some runs. I'm pretty sure that you will get this error after some runs because our used code is exactly the same and it can't be for sure the problem with my keys.

**Comment by mccwdev** [comment]
I've tested 10000 iterations in version 0.4.19 and the latest version but didn't encounter any errors. Cannot think of a way also how the raw transaction can be identical but the signatures not, because the signatures are part of the raw transaction... Are you sure the code example is the same as the one you have tested?  

Maybe one of the dependency packages is different such as fastecdsa. Are you working on a Linux variant or Windows?

And could you check the logs if you see any errors or warning there?

**Comment by Mahsa-Bastankhah** [comment]
yes, I run exactly the same code on a windows os and python 3.6.5. I don't have fastecdsa installed but botcoinlib library works correctly!!!!!! Isn't that weird???
as I told before I don't get any warning or error in python Run console, the only problem is that assert (s == s1) raises an AssertionError and when I broadcast the raw transaction in blockstream manually, I get non-mandatory-verifiable error. I'm totally confused and don't know what to do to solve this!!!

**Comment by mccwdev** [comment]
So you probably using the ecdsa library which uses other methods to create signatures then fastecdsa I think. I will run some tests.

**Comment by Mahsa-Bastankhah** [comment]
you were totally right. I installed the fastecdsa and bitcoinlib on ubuntu and everything got fixed!!
It took about one month for me to find the solution!!!
Thanks for following up. Now I finally close this issue!

**Comment by mccwdev** [comment]
Great to hear you found a working solution!

I would still like to check if there is a problem with the ecdsa or pyscrypt modules in combination with Windows, so I reopen the issue for now.
