### ISSUE TITLE
support bitcoin sv?

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [1200wd/bitcoinlib#139]
does this library can be used to communicate with bitcoin sv blockchain?

**Comment by mccwdev** [comment]
This branch adds bitcoin cash and bitcoin sv: https://github.com/1200wd/bitcoinlib/tree/add-bitcoin-cash
It hasn't been merged to master, because there are not enough reliable service blockchain providers for bitcoin cash en bitcoin sv. So it's hard to use and test.
