### ISSUE TITLE
Sending fraction of bitcoin

### ISSUE THREAD

**Issue by benlvovsky** [1200wd/bitcoinlib#141]
I need to send fractions of bitcoin but send_to() offers onl integer with smallest denominator Satoshi's. What is the formulae to calculate it? Does the the bitcoinlib has it?

**Comment by mccwdev** [comment]
1 bitcoin is 100,000,000 Satoshi's. There no method yet in the library to calculate is but you could use:
```
btc_amount = 0.07
denominator = 100000000
satoshi_amount = btc_amount * denominator
```

You can find the denominator in Network().denominator

**Comment by mccwdev** [comment]
You can also use a string as value when sending bitcoin. This uses the new [Value](https://bitcoinlib.readthedocs.io/en/latest/source/bitcoinlib.values.html) class.

```
t = w.send_to('1PWXhWvUH3bcDWn6Fdq3xhMRPfxRXTjAi1', '0.001 BTC')
# or
t = w.send_to('1PWXhWvUH3bcDWn6Fdq3xhMRPfxRXTjAi1', '1 mBTC')
