### ISSUE TITLE
get_key function returns list of object or a single HDKey object

### ISSUE THREAD

**Issue by cyanlink** [1200wd/bitcoinlib#147]
This behavior leads to inconsistency and maintainability problems and I think refactoring it is needed.
An possible fix would be always return a list, if the caller only expects one result then they can access it with index 0.
What led me here first is the inconsistency in our CLI wallet doc, which says --receive NUM_OF_ADDRESSES, however the actual code says cosigner id. 
If a wallet is non-multisig and user still inputs a cosigner id, the function always returns the address of index 0.

**Comment by mccwdev** [comment]
So yes the CLI wallet is not working correctly and should be fixed.
But for the get_key method returning a list instead of single object when the number_of_keys argument is used. I'm not sure if we should update that. It might be not good practice, but I assume the method is used without the number_of_keys argument 95% of the time and if you use the argument you know you will receive a list.

**Comment by cyanlink** [comment]
Let's take a look at the code. 
If we are using BIP32 then everything is fine, we generate new keys to fill the vacancy if there is no enough unused keys in stock. 
But if it's a scheme='single' wallet, when we have one single unused mainkey, and we try to get 5 keys, we get an HDKey object because we changed number_of_keys in the method which is unexpected by the caller and will raise runtime exception:
```
 if self.scheme == 'single' and len(dbkey):
            number_of_keys = len(dbkey) if number_of_keys > len(dbkey) else number_of_keys
# then the len(key_list) == 1, caller get an HDKey object not a list.
```
and if the only mainkey is used, when scheme=='single', new_key() will always return mainkey. then we get a list containing 5 same mainkey, which is not known by the caller.
I did not find a test function on this in the test folder. maybe we write one and the current code can't pass it.

**Comment by mccwdev** [comment]
See https://github.com/1200wd/bitcoinlib/commit/15bec1a2f52d9c770c8c0f2c6f5b5520a296d9c2 and https://github.com/1200wd/bitcoinlib/commit/b54288e40dbbd68a6086c861a45b2962e47a85f5

Creates a method new_keys which always return a list of keys and the method new_key always returns a single HDKey object. I've also added some extra checks and exceptions to avoid confusion.
