### ISSUE TITLE
Cannot install BitcoinLib in FreeBSD platform.

### ISSUE THREAD

**Issue by labadze** [1200wd/bitcoinlib#149]
When I try install this library on FreeBSD getting following error:

- Python 3.7
- OS freebsd-12.1-RELEASE-amd64

`creating build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa
    copying fastecdsa/point.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa
    copying fastecdsa/__init__.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa
    copying fastecdsa/ecdsa.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa
    copying fastecdsa/benchmark.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa
    copying fastecdsa/curve.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa
    copying fastecdsa/keys.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa
    copying fastecdsa/util.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa
    creating build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/encoding
    copying fastecdsa/encoding/util.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/encoding
    copying fastecdsa/encoding/pem.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/encoding
    copying fastecdsa/encoding/sec1.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/encoding
    copying fastecdsa/encoding/__init__.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/encoding
    copying fastecdsa/encoding/asn1.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/encoding
    copying fastecdsa/encoding/der.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/encoding
    creating build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    copying fastecdsa/tests/test_prehashed.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    copying fastecdsa/tests/test_whitespace_parsing.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    copying fastecdsa/tests/test_nonce_generation.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    copying fastecdsa/tests/__init__.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    copying fastecdsa/tests/test_keygen.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    copying fastecdsa/tests/test_p256_ecdsa.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    copying fastecdsa/tests/test_brainpool_ecdh.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    copying fastecdsa/tests/test_point.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    copying fastecdsa/tests/test_prime_field_curve_math.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    copying fastecdsa/tests/test_rfc6979_ecdsa.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    copying fastecdsa/tests/test_whycheproof_vectors.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    copying fastecdsa/tests/test_key_recovery.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests
    creating build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests/encoding
    copying fastecdsa/tests/encoding/test_asn1.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests/encoding
    copying fastecdsa/tests/encoding/test_der.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests/encoding
    copying fastecdsa/tests/encoding/__init__.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests/encoding
    copying fastecdsa/tests/encoding/test_sec1.py -> build/lib.freebsd-12.1-RELEASE-amd64-3.7/fastecdsa/tests/encoding
    running build_ext
    building 'fastecdsa.curvemath' extension
    creating build/temp.freebsd-12.1-RELEASE-amd64-3.7
    creating build/temp.freebsd-12.1-RELEASE-amd64-3.7/src
    cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -Isrc/ -I/usr/local/include/python3.7m -c sradoramus@srv:~ % 
    In file included from src/curveMath.c:1:
    src/curveMath.h:6:10: fatal error: 'gmp.h' file not found
    #include <gmp.h>
             ^~~~~~~
    1 error generated.
    error: command 'cc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g70lp84y/fastecdsa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g70lp84y/fastecdsa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yv3d67gv/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/user/.local/include/python3.7m/fastecdsa Check the logs for full command output.`

**Comment by mccwdev** [comment]
This seems related to the fastecdsa package. Have you installed the required packages? See https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.install.html#other-requirements-linux and https://github.com/AntonKueltz/fastecdsa#installing
