### ISSUE TITLE
NetworkError: Network dogecoin not found in network definitions

### ISSUE THREAD

**Issue by parizad1188** [1200wd/bitcoinlib#151]
Hi,
I have installed "bitcoinlib" library. When I want to use it in python project to create_transaction, I get this error:

Could not import all modules. Error: No module named 'mysql'
bitcoinlib.networks.NetworkError: Network dogecoin not found in network definitions

So how could I fix this? what's the point?

Thanks,

**Comment by mccwdev** [comment]
Have you installed the library with pip?  Could it be that you upgraded / reinstalled the library, and there was a previous version installed? In that case you could try to remove the install.log file, so the settings files we be recopied. See https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.install.html#update-bitcoinlib

**Comment by parizad1188** [comment]
Thanks. that was exactly the problem. However, the location of the install.log was not exactly the same as the manual suggested. For me it was located in ~/.bitcoinlib/install.log 
regards,

**Comment by mccwdev** [comment]
You're right, thanks, I have updated the documentation.
