### ISSUE TITLE
dash privatesend

### ISSUE THREAD

**Issue by benlvovsky** [1200wd/bitcoinlib#156]
Hi,
As far as I understood bitcoinlib also handles dash and bch. How do I PrivateSend dash?

Thank you in advance,
Ben

**Comment by mccwdev** [comment]
Unfortunately this is not supported at the moment

**Comment by mccwdev** [comment]
Support for dash network will be removed from this library in version 0.7
Unfortunately there are not enough api service providers to get it working reliable.
