### ISSUE TITLE
Is this a problem?

### ISSUE THREAD

**Issue by Gitcqs** [1200wd/bitcoinlib#157]
The scenario is as follows. After the payment address is generated, the key instance is obtained through Wallet.key(), and the balance is checked for the specified address. Then the actual situation will not meet expectations, because the wallet will cache the key instance in _key_objects and the data will never be updated. Either re-instance a wallet or can only check whether the address has been paid by other methods (utxos)

**Comment by mccwdev** [comment]
You could also use the keys() method to get the latest key data and balance from the database.

But you are right the data from the key() method is cached in the object and never updated, which is not what you expected when you retrieve the balance. So probably the balance should not be cached, let me think of a solution.
