### ISSUE TITLE
Can I restore wallet from mnemonic (seed)?

### ISSUE THREAD

**Issue by kvbogdanov** [1200wd/bitcoinlib#16]
I've just carefully read code and documentation, but can't find a way to restore wallet from seed. Can you show me small example, please?

**Comment by mccwdev** [comment]
It depends on which format your seed is, but you need to create a HDKey object first and then use this key to create a new wallet:

 hdkey = HDKey().from_seed(your_seed)
 wallet = HDWallet.create(name='Wallet', key=hdkey)

**Comment by kvbogdanov** [comment]
Thanks!

But how can I get a balance of this wallet?

Trying this:
`wallet = HDWallet.create(name='Wallet_test', key=hdkey, network='bitcoin')
wallet.balance_update(network='bitcoin')
balance = wallet.balance(network='bitcoin', as_string=True)`

**Comment by mccwdev** [comment]
The balance_update method makes the calculation from the database, but if the transactions are not up to date nothing happens.

It better to use the utxos_update() method, this gets all the unspent outputs from a service provider like blockchain.info and then updates the balance as well.

**Comment by kvbogdanov** [comment]
Where can I see some examples for gettin' info from UTXO? Using utxos_update() still returned zero balance.

Thanks!

**Comment by mccwdev** [comment]
Are all the keys/addresses generated in the wallet? Use new_key() or new_key_change() for this.

See https://github.com/1200wd/bitcoinlib/blob/82f7fff39295c9494444721abb698c68f4a63bf9/examples/wallets.py#L142-L155

**Comment by kvbogdanov** [comment]
Thanks a lot for response!

I didn't generate additional addresses for wallet by myself, I just want to get balance for existed wallet. Now I got this (based on example, for the wallet, restored from existed phrase):

`- Network: bitcoin -
   50 m                            165d63qWrxwb8a4uDNzhs8F5aTLQvmwazr            Wallet_test_4                        0.00000000 BTC
   51 m/44'                        1N52C6u4sKDoxVbfaDAvPHYWaGNvifgxxv            Wallet_test_4                        0.00000000 BTC
   52 m/44'/0'                     1HHQJ9inew4NJLyYdgBNabKtEeAFuCz54K            Wallet_test_4                        0.00000000 BTC
   53 m/44'/0'/0'                  1XBCrgXp8pN3149GcRxkB9KAtZuSAwJYd             Account #0                           0.00000000 BTC
   54 m/44'/0'/0'/0                1HfEJtPUAa8qKTYbwvxc2kjcJysinR2Q9c            Account #0 Payments                  0.00000000 BTC
   55 m/44'/0'/0'/1                1DY67sQjxhXw93PZwzd8AqLJTfP3BsJ1cT            Account #0 Change                    0.00000000 BTC`

On the first sight, all addresses correct, but I can't understand why I've got zeros (actually not). May be, I'am incorrect work with provider?

**Comment by mccwdev** [comment]
I'm traveling sorry for my slow response. If there are any problems with the providers they should be visible in de logs: ~/.bitcoinlib/log/bitcoinlib.log  But normally it should work without extra settings.
But if you look up the address on a blockchain explorer you see a balance?

**Comment by kvbogdanov** [comment]
Yes, there is a positive balance on wallet addresses. But (as I see in the log) there is no UTXO's for them:

```
2018/01/08 22:07:23 INFO <module>(79) WELCOME TO BITCOINLIB - CRYPTOCURRENCY LIBRARY
2018/01/08 22:07:23 INFO <module>(80) Logger name: logging
2018/01/08 22:07:24 INFO <module>(35) Using Database /Users/konstantin/.bitcoinlib/database/bitcoinlib.sqlite
2018/01/08 22:07:24 INFO create(507) Create new wallet 'Wallet_test_4'
2018/01/08 22:07:24 INFO __init__(745) Opening wallet 'Wallet_test_4'
2018/01/08 22:07:24 INFO _create_keys_from_path(694) New key(s) created for parent_id 52
2018/01/08 22:07:24 INFO _create_keys_from_path(694) New key(s) created for parent_id 53
2018/01/08 22:07:24 INFO _create_keys_from_path(694) New key(s) created for parent_id 54
2018/01/08 22:07:25 INFO _create_keys_from_path(694) New key(s) created for parent_id 55
2018/01/08 22:07:25 INFO utxos_update(1817) Got 0 new UTXOs for account 99
2018/01/08 22:07:25 INFO balance_update(1703) Got balance for 0 key(s)
2018/01/08 22:07:25 INFO balance_update(1703) Got balance for 6 key(s)
2018/01/08 22:07:25 INFO balance_update(1703) Got balance for 6 key(s)
2018/01/08 22:07:25 INFO balance_update(1703) Got balance for 6 key(s)
```
I'm definitely doing something wrong,  but can't see what exactly (

**Comment by mccwdev** [comment]
It's hard to see what is wrong, nothing in the logs. Are you using the latest version of bitcoinlib?
What you can try is updating the utxo for the specific key only:
 wallet.utxo_update(key_id=[key_id])
and also check if anything shows up in the logs then.
And I see it's only updating the keys of account 99, is that your intention?
