### ISSUE TITLE
Error in utxos_update()

### ISSUE THREAD

**Issue by flqrian** [1200wd/bitcoinlib#160]
Hi, there is an error while triggering utxos_update : 

 File "/home/flo/nodes/venv/lib/python3.6/site-packages/bitcoinlib/wallets.py", line 2774, in utxos_update
    filter_by(wallet_id=self.wallet_id, txid=bytes.fromhex(utxo['txid']),
TypeError: fromhex() argument must be str, not bytes

Which is true because the txid field in DbTransaction class is a bytes ..

Anyone to help ?

Regards

**Comment by mccwdev** [comment]
The utxo set should only contain hexadecimal strings, so the error is not in this part of the code. It could be one of the blockchain service providers returning bytes instead of string. But I cannot find any errors in the code.

Can you try to reproduce and see in the logs which service provider is being used or may if there in another error?

**Comment by pabmac** [comment]
Hello, I copy you an response that I have from the services and the possible solution that I found:
**Response**:
[{'address': 'mtBxnniJtotpRMcXeq9i9WEz6SsMdud', 'txid': b'h\xa62\xf1g\xaf\x95\xee\xb5\xa3\xa7\xf0T\x06\xf8\n\x8f\xbbv\xd4\xe2yE\xe8;\xc0d\xee\xafpM\x96', 'confirmations': 1, 'output_n': 0, 'input_n': 0, 'block_height': 1936825, 'fee': 1011, 'size': 0, 'value': 1890, 'script': '', 'date': datetime.datetime(2021, 2, 19, 14, 24, 38)}]
**Possible Solution's**:
if type(utxo['txid']) == type(bytes()):
          __txid = utxo['txid']
      else:
          __txid = bytes.fromhex(utxo['txid'])
      # Update confirmations in db if utxo was already imported
      transaction_in_db = self._session.query(DbTransaction).\
          filter_by(wallet_id=self.wallet_id, txid=__txid,
                    network_name=self.network.name)
      utxo_in_db = self._session.query(DbTransactionOutput).join(DbTransaction).\
          filter(DbTransaction.wallet_id == self.wallet_id,
                 DbTransaction.txid == __txid,
                 DbTransactionOutput.output_n == utxo['output_n'])
      spent_in_db = self._session.query(DbTransactionInput).join(DbTransaction).\
          filter(DbTransaction.wallet_id == self.wallet_id,
                 DbTransactionInput.prev_txid == __txid,
                 DbTransactionInput.output_n == utxo['output_n'])

Best Regars

**Comment by mccwdev** [comment]
Thanks for your tests. The response shouldn't return the txid in bytes. Can you see which service provider creates this response earlier in the logs?

**Comment by flqrian** [comment]
Him

thanks for your answer.

i can confirm pabman's  answer, and i did the same workaround locally.

I'am using bitcoin core (bitcoind) as a service provider.

**Comment by mccwdev** [comment]
Encoding problem fixed in https://github.com/1200wd/bitcoinlib/commit/35951914f96dcb642c9de65ede6230262695d6b1
Problem seems to occur when transactions are retrieved from cache.
