### ISSUE TITLE
How to derive addresses with a hierarchical key ("xpub") of a Bitcoin Hardware wallet?

### ISSUE THREAD

**Issue by j4nos** [1200wd/bitcoinlib#161]
I need derive around 100 addresses from a hierarchical key ("xpub") in Python. Do you know how?

With `bitcoinlib ` I can generate / derive address from a Wallet, but I have only "xpub" available.

```python
w = Wallet.create("Wallet2", keys=passphrase, network='bitcoin')
account_btc2 = w.new_account('Account BTC 2')
```

**Comment by mccwdev** [comment]
You could do 
```
keys = w.get_keys(number_of_keys=10)`
```

or

```
keys = []
    for _ in range(100):
        keys.append(w.new_key())
```

The first gets 100 unused keys from the wallet even if they are generated before. The second generates 100 new keys, and ignores already created keys.
