### ISSUE TITLE
How to specify the address to send remaining amount of a transaction with to_send()

### ISSUE THREAD

**Issue by flqrian** [1200wd/bitcoinlib#164]
Hi,

when i use the 'to_send()' function to send fund to one address, the remaining amount of the input is sent to a random address from my wallet. 

I would like to send this remaining amount to the same address everytime i use the to_send() function, but i dont see any parameter to set it.

Could you help me ?

regards

**Comment by mccwdev** [comment]
There are several ways to do this, although I wouldn't recommend it as it reduces your privacy.

You could create a transaction and add the inputs and outputs yourself. Another trick is to use the sweep method and limit it to a specific key:
```
return_key = w.key(return_key_id)
to_list = [
    (addres, 20000),
    (return_key.address, 0)
]
t = w.sweep(to_list, input_key_id=return_key.key_id)
```

**Comment by flqrian** [comment]
Thanks for your answer.

I saw the sweep method, but with my current app, i should only use 2 outputs. The first with the specified amount, and another specified address to receive the remaining amount.

I guess in your example that the 0 amount for the second address will send all remaining amount of the input to this one ?

If not, do you have an example to perform this ?

Regards

**Comment by mccwdev** [comment]
Yes indeed, the address with the 0 amount will be used as change output.

Copy-n-paste from the latest docstring:

        >>> to_list = [('1J9GDZMKEr3ZTj8q6pwtMy4Arvt92FDBTb', 100000), (w.get_key(), 0)]
        >>> w.sweep(to_list, offline=True)
        <WalletTransaction(input_count=1, output_count=2, status=new, network=bitcoin)>

        :param to_address: Single output address or list of outputs in format [(<adddress>, <amount>)]. If you specify a list of outputs, use amount value = 0 to indicate a change output
        :type to_address: str, list

**Comment by flqrian** [comment]
thanks for your answer.

Unfortunately i want to send a transaction to an output that is not on my wallet (external address). I think the sweep method is good to send utxos from your wallet to another address from your wallet. (correct me if i'am wrong)

the thing i did is this : 
send_addresses = [(withdrawal.address, amount), (settings.receive_address, 0)]
transaction = w.send(send_addresses)

Like this it work perfectly. the first output receive the good amount, and the other one receive 0.

However, i dont know if this is a good practice to send 0 satoshi in an output .

If you have a better solution, let me know.

Regards

**Comment by flqrian** [comment]
Thank you for your answer.

Unfortunately the sweep does not really fit with my need and how my custom app works.

Is it possible to specify a change address with the send() or create_transaction() method ?

**Comment by mccwdev** [comment]
With the send method you can send to a list of addresses which may also include a change address. Then you need to select a utxo yourself and include the input_key_id.

**Comment by lyonkvalid** [comment]
> With the send method you can send to a list of addresses which may also include a change address. Then you need to select a utxo yourself and include the input_key_id.

Pls how can i calculate transaction fee before pushing to the network , i am building a crytocurrency website , user have to know their transaction fees

**Comment by mccwdev** [comment]
See https://github.com/1200wd/bitcoinlib/issues/167 for an example
