### ISSUE TITLE
No successful response from any serviceprovider: ['litecoind.testnet']

### ISSUE THREAD

**Issue by flqrian** [1200wd/bitcoinlib#166]
Hi,

i'am trying to connect to a local litecoin testnet (litecoind testnet).

I added this service provider in .bitcoinlib/providers.json : 

  "litecoind.testnet": {
    "provider": "litecoind",
    "network": "litecoin_testnet",
    "client_class": "LitecoindClient()",
    "provider_coin_id": "",
    "url": "http://litecoinrpc:testnetpsw@localhost:18335",
    "api_key": "",
    "priority": 10,
    "denominator": 100000000,
    "network_overrides": null
  },

 in .bitcoinlib/litecoin-testnet.conf, which is the same conf i use when in launch my local litecoind testnet blockchain : 

[rpc]
rpcuser=litecoinrpc
rpcpassword=testnetpsw
server=1
port=18335
txindex=1
testnet=1

i got this error when i try to scan, utxos_update and other methods linked to the blockchain : 

WARNING:bitcoinlib.services.services:No successful response from any serviceprovider: ['litecoind.testnet']
ERROR:bitcoinlib.services.services:Error when retrieving transactions from service provider.

there is no other informations in the log.

thanks for your help

**Comment by tomjeannesson** [comment]
Hello @barbat0x !
I am having an issue with `No successful response from any serviceprovider` too, but for the regular litecoin_testnet.
How did you fix it?
