### ISSUE TITLE
How can i calculate transaction fees

### ISSUE THREAD

**Issue by lyonkvalid** [1200wd/bitcoinlib#167]
I am building a P2P crytocurrency app , pls how can i know the transaction fee calculate by the library before sending to the network?

Like i should know 

I BTC = 0.0001 fee

**Comment by mccwdev** [comment]
You can create a transaction and not send it by use the 'offline' argument and set it to True in the send, send_to or sweep method:

```
t = w.sweep('1J9GDZMKEr3ZTj8q6pwtMy4Arvt92FDBTb', offline=True)
```

Or you determine the fee first and pass it as 'fee_per_kb' argument when sending a transaction:

```
fee_per_kb = Service().estimatefee()
t = w.sweep('1J9GDZMKEr3ZTj8q6pwtMy4Arvt92FDBTb', fee_per_kb=fee_per_kb)
