### ISSUE TITLE
Use within Lambda

### ISSUE THREAD

**Issue by rhamnett** [1200wd/bitcoinlib#168]
Hello, AWS Lambda has a read only home filesystem. This also means I cannot create a "~/.bitcoinlib/config.ini" to set BCL_DATA_DIR etc

I had a look at the docs but I couldn't see how to specify a different data directory for the database etc. 

Is this currently possible? If so, how do I instantiate at the top of my script with a different location. Thanks

**Comment by mccwdev** [comment]
You can specify the location of the config file in the BCL_CONFIG_FILE enviroment variable.
Please let me know if that works for you.

**Comment by rhamnett** [comment]
Thanks, yes sorry should have looked better in the config section. Appreciate the reply.
