### ISSUE TITLE
Dash send_to "Missing inputs"

### ISSUE THREAD

**Issue by ali-ghn** [1200wd/bitcoinlib#169]
hey
when i want to make a transaction using `send_to` method it doesn't show up in blockchain and when i was debugging i saw service providers throwing "Missing inputs" exception.
i tested Litecoin and it works fine but there seems to be an issue with Dash

**Comment by mccwdev** [comment]
I couldn't find any problems, could you check which service provider threw the missing input exception?

**Comment by ali-ghn** [comment]
It was an old version, i was able to use Dash with the newest version.
Thank you.
