### ISSUE TITLE
How to see list of received CRYTO and sent Crypto with amount and sender's address / receiver address

### ISSUE THREAD

**Issue by lyonkvalid** [1200wd/bitcoinlib#171]
I want to create a notification , when ever the user received new fund the wallet automatically create a notification 

`You received 0.00005 BTC worth $40 from address`

I already have an API to handle the price , the problem is sorting utxos that are from receive funds and send funds

**Comment by mccwdev** [comment]
The wallet and service providers always return all utxo's. But I think you can solve this with Python and compare the new and old list of utxo's to determine which utxo's are new.

**Comment by lyonkvalid** [comment]
How can i do that ? I want my program to be faster , due to the wallet status now , i think the wallet is slow to start with , i can't risk sorting a big utxo in near future the time complexity is high , can you suggest an faster algorithm to do this?

**Comment by mccwdev** [comment]
The wallets depends on external service providers, and those API queries cost time.
If you want to make your application faster you can run a local bitcoind or bcoin node.
