### ISSUE TITLE
Add RBF support

### ISSUE THREAD

**Issue by gcomte** [1200wd/bitcoinlib#179]
Add support for replace-by-fee according to [BIP 125](https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki9).

Transaction need to be flagged as RBF transactions, if there should be a possibility to RBF them later.

**Comment by mccwdev** [comment]
Add replace-by-fee option to Wallet, Transaction and commandline wallet in release 0.7
commit 11c2857cb356f9289513665cc793cfb8d9b1e462
