### ISSUE TITLE
Transaction with several utxos

### ISSUE THREAD

**Issue by caqs** [1200wd/bitcoinlib#18]
Hi everyone!

I'm trying to make a Transaction from an address that has several utxos. If I build an array of Inputs, and then make the Transaction it fails:

############# Balance=1BTC / utxo1[value]=0.5BTC / utxo2[value]=0.5BTC ############# 
inp1 = Input(prev_hash='xxxxx',output_index=0,keys=pubkey.public(), network='testnet') #from utxo1
inp2 = Input(prev_hash='yyyy',output_index=0,keys=pubkey.public(), network='testnet') #from utxo2
out   = Output(100000000, address=addr_to, network='testnet')

t = Transaction(inputs=[inp1,inp2],outputs=[out], network='testnet')
t.sign(private)
t.verify()  # **False**

But if I try to make a Transaction only using the information from one utxo, it's completed ok:

############# Balance=1BTC / utxo1[value]=0.5BTC / utxo2[value]=0.5BTC ############# 
inp1 = Input(prev_hash='xxxxx',output_index=0,keys=pubkey.public(), network='testnet') #from utxo1
out   = Output(50000000, address=addr_to, network='testnet')

t = Transaction(inputs=[inp1],outputs=[out], network='testnet')
t.sign(private)
t.verify()  # **True**

Is there any way to build a Transaction from several utxo's?

**Comment by mccwdev** [comment]
Yes there seems to be a problem in the verify method, will take a look into it.

**Comment by mccwdev** [comment]
It's the sign method, it doesn't sign the second input because it uses the same key.
You can sign it like this to workaround this issue:
`t.sign(private, tid=0)`
`t.sign(private, tid=1)`

**Comment by mccwdev** [comment]
Your code should work as expected after this branch is merged:
https://github.com/1200wd/bitcoinlib/tree/fix-duplicate-key-inputs

**Comment by caqs** [comment]
Thanks a lot! I'm trying this way before going to another branch.

Regards!
