### ISSUE TITLE
How to restore wallet?

### ISSUE THREAD

**Issue by gddip189** [1200wd/bitcoinlib#180]
Sir 
I am a beginner 
Suppose I created a wallet and added 1 BTC 
Now I turned off my pc
How can I use that wallet
Please reply

**Comment by mccwdev** [comment]
The wallet are stored in a sqlite database in your home folder.

You can open a wallet by passing a name or wallet ID:
 w = Wallet(<wallet_name / wallet_id>)
 w.info()  # to show wallet information
