### ISSUE TITLE
[Question] Selfhosting a provider

### ISSUE THREAD

**Issue by sokripon** [1200wd/bitcoinlib#190]
Hello, I already have a litecoind running but it doesn't cover every request that is made. As far as I understand, I would need a database that is heavily indexed for all the functionality that services like chain.so offer.
So my question is, are there any open-source self-hostable variants of services like chain.so?
(My main goal is to rely as little as possible on 3rd party APIs. I also only need this for litecoin, but it doesn't matter if it covers other cryptos too.)

**Comment by mccwdev** [comment]
There is block explorer we have created with a web backend https://github.com/1200wd/blocksmurfer.  But then you still indirectly dependent on 3rd party API providers. 

So I would use the bcoin node, for my experiences see https://coineva.com/using-bcoin-node-with-bitcoinlib.html. There is also a version for Litecoin, but I haven't used that yet.

**Comment by sokripon** [comment]
Thanks!
bcoin/lcoin was exactly what I was looking for.
