### ISSUE TITLE
Incorrect Currency Symbol Used for Bitcoin 

### ISSUE THREAD

**Issue by danieldjewell** [1200wd/bitcoinlib#193]
The symbol used for Bitcoin is incorrect. The symbol in the data file is Unicode 0x0e3f (&#xe3f;) which is the symbol for the [Thai baht](https://en.wikipedia.org/wiki/Thai_baht) ... the correct symbol (which is now in Unicode) is 0x20bf (&#x20bf;)

https://github.com/1200wd/bitcoinlib/blob/daf731d86829e22a99d1222af4ab7efb6e6ffcf4/bitcoinlib/data/networks.json#L40

If you'd like, I can make a PR....

**Comment by mccwdev** [comment]
Yes you are right, not a lot of fonts supported the Bitcoin symbol a while ago, so we the used the Thai Baht symbol.
If you could create a PR that would be great..

**Comment by mccwdev** [comment]
Thanks 👍
