### ISSUE TITLE
Connection to local bitcoind instance

### ISSUE THREAD

**Issue by caqs** [1200wd/bitcoinlib#20]
Hi everyone!

Just a simple question: is there any way to connect to a local instance of **bitcoind** daemon via bitcoinlib and use it to send raw transactions?

If it's possible, do you have an example to perform that connection and transaction?

_Thanks a lot!_

**Comment by mccwdev** [comment]
It should connect to a local bitcoin deamon automatically, although I didn't test this for a while.
You can try to specify settings the .bitcoinlib/config/bitcoin.conf file, this is just a copy of the bitcoind config file.
Once a connection is established you can use the sendrawtransaction() method.

**Comment by caqs** [comment]
I'll try it. Thanks for the tip.
