### ISSUE TITLE
Fee estimation occasionally suggests 104 sat/B even when network is not congested

### ISSUE THREAD

**Issue by NateNate60** [1200wd/bitcoinlib#201]
I noticed something off when my program was suggesting 104 sat/B to users today even though the network is relatively uncongested. I've nailed it down to something with `bitcoinlib`'s fee estimation, which seems to strangely (and somewhat randomly) return 104,448 sat/kB as the suggested feerate.

```
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitcoinlib
>>> fee = bitcoinlib.services.services.Service(network="bitcoin")
>>> fee.estimatefee(1)
104448
>>>
```

This occurred at UNIX time 1635471356 (29 Oct 2021 01:35:56 GMT), on both my personal PC and my server. At that time, the suggested feerate according to Blockchair was 1 sat/B and according to Mempool.space it was 2 sat/B, meaning it was off by more than an order of magnitude. PC runs Ubuntu 21.10 and the server runs Ubuntu 20.04, if that matters. Both are using `bitcoinlib` as installed using `pip3`.

Sometimes this issue occurs, sometimes it does not. I wasn't able to attribute any clear pattern in terms of what causes it to happen. Ah, the bane of any developer. Not just an error, but a *randomly occurring error*. Or maybe I'm using the library wrong. The documentation is a bit arcane.

Edit: I dug up an old complaint from a user from two months ago where the suggested feerate was *also* 104448. There appears to be something special about 104448, but I wasn't able to deduce *what* was so special.

**Comment by NateNate60** [comment]
I solved the issue (at least for my use case) by just using `requests` to fetch information from mempool.space:

```
>>> import requests
>>> requests.get("https://mempool.space/api/v1/fees/recommended/").json()['fastestFee']
1
```

This is fundamentally just what `bitcoinlib` does under the hood anyway. I've personally found that mempool.space gives the most accurate fee estimations, but that's only my opinion. Other users may prefer Blockchair:

```
>>> requests.get("https://api.blockchair.com/stats/").json()['data']['bitcoin']['data']['suggested_transaction_fee_per_byte_sat']
1
```

...but the Blockchair API enforces rate limits, meaning in some shared hosting environments your IP will be blocked for excessive use if any of your neighbours are using it too much. Mempool.space doesn't have API limits, which makes it suitable for my usecase.

**Comment by mccwdev** [comment]
Coinfees provider has been removed in commit  https://github.com/1200wd/bitcoinlib/commit/b62b7f792cea0e76074b620fa2ce608095d3573d

The mempool.space providers looks nice, I will run some tests and see if I can add it to the next release.
