### ISSUE TITLE
Update unsupported numpy dependency on Apple Silicon

### ISSUE THREAD

**Issue by dvf** [1200wd/bitcoinlib#204]
I'm unable to install this library on an Apple M1 Silicon chip.

See Numpy issue here: https://github.com/numpy/numpy/issues/18160.

Can confirm installation works for `numpy = "^1.21.4"`. Would it be possible to bump?

**Comment by dvf** [comment]
I noticed that the outdated version is set here: https://github.com/1200wd/bitcoinlib/blob/master/setup.py#L46
but it looks like it's been updated in `requirements.txt`.

**Comment by dvf** [comment]
Thanks for merging the PR @mccwdev. Can you do a version bump and upload to PyPI? Right now 0.6.2 is uninstallable on Apple Silicon.

**Comment by mccwdev** [comment]
Not at this moment sorry. It needs some more testing, and also I will need to replace or fix Travis.

Maybe you can try to install from Github?
