### ISSUE TITLE
Missing litecoin transactions

### ISSUE THREAD

**Issue by manbehindthemadness** [1200wd/bitcoinlib#214]
Perhaps I am just looking at this wrong, but I seem to be having an issue with litecoin transactions coming from the same sender going missing. The first transaction arrives promptly with no issue; however, the second one never seems to be picked up during the scan.
Example: 
https://blockchair.com/litecoin/address/Lc5Qq4sQC4SN2hxHQrQRkoi7UDS21HsG2D
https://pastebin.com/HLkJeYvK

**Comment by mccwdev** [comment]
Could you check the logs in bitcoinlib.log to see which providers are used and if some providers return errors, warnings or incorrect data?

**Comment by manbehindthemadness** [comment]
Thanks for the reply! So I scraped the SQLite files and re-populated using a segwit wallet instead of legacy and it seems the problem is resolved. I can still dig out the log if you like.
