### ISSUE TITLE
all my wallets have a private key that starts with the same 12 characters

### ISSUE THREAD

**Issue by krupan** [1200wd/bitcoinlib#215]
I can delete my ~/.bitcoinlib directory and re-run my code and all my wallets still always have a private key that starts with the same 12 characters (16 if you include the zprv).  This doesn't seem right.  Is there not enough randomness on my system!?
```
seed_phrase = Mnemonic('english').generate(256)
w = Wallet.create(name, keys=seed_phrase, network='bitcoin', witness_type='segwit')
print(w.keys()[0])
```
First 12 characters are always the same.

**Comment by mccwdev** [comment]
The first part contains information about the key depth, parent fingerprint and child which is the same for all masterkeys.

Here you can see how the WIF key is build. The last 32 bytes contain the private key. 
https://github.com/1200wd/bitcoinlib/blob/0de3b77950d67c8d6fb78a1979a8af41ad1b63e0/bitcoinlib/keys.py#L1558-L1559
