### ISSUE TITLE
Version 0.3.33a0 with python3

### ISSUE THREAD

**Issue by Menetar** [1200wd/bitcoinlib#22]
Hey there guys!

I was working with python 2.7.12 and decided to change all my work to python 3.5.2. I managedd to use python 3 without trouble with bitcoinlib 0.3.29 but as I upgraded to 0.33.a0, I've been having trouble using Key(network=network_id,passphrase=passphrase_msg) for creating a new address. 

It returns an error: [ KeyError: 'dust_amount' ] 

The traceback is:
var = Key(network=network_id,passphrase=passphrase_msg)
  File "/usr/local/lib/python3.5/dist-packages/bitcoinlib/keys.py", line 304, in __init__
    self.network = Network(network)
  File "/usr/local/lib/python3.5/dist-packages/bitcoinlib/networks.py", line 166, in __init__
    self.dust_amount = NETWORK_DEFINITIONS[network_name]['dust_amount']

This does work on python 2.7. Did I miss anything about using the latest version with python 3?

Thanks!

**Comment by mccwdev** [comment]
You can fix this by deleting the .bitcoinlib/log/install.log file.

The dust_amount field was added to the networks.json settings file and if you delete the install log file the new network (and provider) settings file will be copied.

If you made some changes to the networks.json or provider.json file manually you will loose these changes and have to make them again.

**Comment by Menetar** [comment]
Thanks mccwdev, that solved the issue.
