### ISSUE TITLE
encrypting privatekeys field in sqlalchemy

### ISSUE THREAD

**Issue by alinik** [1200wd/bitcoinlib#220]
Hi,
Is there any plan to protect privatekeys (and maybe wif) Columns in Databases? There is a good way [SymmectricClientEncyprtion](https://github.com/sqlalchemy/sqlalchemy/wiki/SymmetricEncryptionClientSide) for postgresql.
I think we can add this feature by modifing [class DbKey](https://github.com/1200wd/bitcoinlib/blob/master/bitcoinlib/db.py#L209).
Thanks

**Comment by mccwdev** [comment]
Yes that might be a good idea, I will take a look into it.

It is possible to encrypt the full database using sqlcipher at the moment, but this needs some extra install: https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.sqlcipher.html

**Comment by mccwdev** [comment]
All private key fields can be encrypted now, see commit 553df0e72892c35f217375b6704f240bace2d3aa
