### ISSUE TITLE
getutxos from bitcoind

### ISSUE THREAD

**Issue by titoli11** [1200wd/bitcoinlib#224]
Hey guys, thanks for a awesome module, im here to ask a noob question.. After fiddeling around i'm struggeling with the function getutxos from bitcoind network,  its giving me the error:
 bitcoind.py", line 149, in getutxos
    assert(self.network == 'regtest')

From my understanding to be able to get around this I have to create a wallet in the bitcoind and then use the import address rpc function to scan for balances?
Would appreciate any input

**Comment by mccwdev** [comment]
The getutxos method is disabled on the BitcoindClient for mainnet and testnet, because it would require to import each address individually and then rescan the full blockchain. Maybe there is a workaround but I haven't found it. 

You could use the bcoin client as alternative.
