### ISSUE TITLE
Create many addresses

### ISSUE THREAD

**Issue by fh0enix** [1200wd/bitcoinlib#228]
Create many addresses.

I need to create 10,000 **uncompressed** bitcoin addresses and write this to a text file.

Addresses must be generated from private keys that will be generated **sequentially**.

Example:
Generate a **sequence** of private keys from 1 to 10,000 and write public addresses in a text file.
Or Generate a **sequence** of private keys from 1577898802222233 to 1577898902222233 and write public addresses in a text file.

Who can help with the code for this?

Thank you))

**Comment by mccwdev** [comment]
You can create a wallet for this and use the get_keys() method to generate new addresses.
```
w = Wallet.create('wallet228')
keys = w.get_keys(number_of_keys=10)
```

**Comment by fh0enix** [comment]
> You can create a wallet for this and use the get_keys() method to generate new addresses.
> 
> ```
> w = Wallet.create('wallet228')
> keys = w.get_keys(number_of_keys=10)
> ```

TypeError: get_key() got an unexpected keyword argument 'number_of_keys'

**Comment by mccwdev** [comment]
The method is get_keys() with keys in plural.
