### ISSUE TITLE
Not able to make transaction using seedphrase. "No UXTO's found"

### ISSUE THREAD

**Issue by anthonybudd** [1200wd/bitcoinlib#232]
I have a wallet that has ~$100 of BTC on it. I'm trying to make a programmatic transaction using Bitcoinlib but I am getting this error:

`bitcoinlib.wallets.WalletError: Create transaction: No unspent transaction outputs found or no key available for UTXO's`

In the code I am loading the seedphrase for the wallet with the $100 wallet (line 7, mainKey...). As per the docs I am using the scan() method to _Update all UTXO’s and balances_. I would have thought the scan method would find that there is a balance however the error would suggest that it is not.

Can anyone point out something obvious I'm doing wrong or is this an issue with the library?. 

CODE:
```py
from bitcoinlib.wallets import Wallet
from bitcoinlib.keys import HDKey
import random
import string

walletName = 'MAIN-'+''.join(random.choices(string.ascii_lowercase, k=10))
mainKey = HDKey().from_seed("SEED PHRASE SEED PHRASE SEED PHRASE SEED PHRASE SEED PHRASE SEED PHRASE")
mainWallet = Wallet.create(name=walletName, keys=mainKey)
mainWallet.scan()
mainWallet.info()

anotherWallet = "SEED PHRASE SEED PHRASE SEED PHRASE SEED PHRASE SEED PHRASE SEED PHRASE"
anotherWalletName = ''.join(random.choices(string.ascii_lowercase, k=10))
k = HDKey().from_seed(anotherWallet)
w = Wallet.create(name=anotherWalletName, keys=k)
address = w.get_key().address
print(address)
tx = mainWallet.send_to(address, '0.00001958 BTC')
tx.info()
```

**Comment by mccwdev** [comment]
I could not reproduce the error using the same code. Are you using the latest version of the library?

If so please let me know if you found any errors in the logs.

**Comment by blcklptn** [comment]
Hey, I have the same problem.
![shot](https://user-images.githubusercontent.com/73552143/219000498-8d715ffa-770b-4d08-bd1c-0a13be8684b6.png)

**Comment by felixcheruiyot** [comment]
I experienced this issue and noticed to resolve you simply need to run `utxos_update()`

Basically do a scan and then an update

    w=Wallet(name)
    w.scan()
    w.utxos_update()
