### ISSUE TITLE
Invalid transaction. Error: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation)

### ISSUE THREAD

**Issue by b0r1ngx** [1200wd/bitcoinlib#237]
First i explained my code (i based and code on error and solution by man here (https://stackoverflow.com/questions/71652047/how-to-create-and-broadcast-tx-with-multiple-inputs-in-python-bitcoinlib)

It happens both in EXODUS and ELECTRUM wallet (if i try to send from one or other)

`
from_privkey = 'MY_EXODUS_WALLET_PRIV_KEY'
fr_address = 'bc1qcukaxcksd400rwh5kyd5y57tfvka4n6ngkd5fz'
to_address = 'bc1qm6mdcmhgszfmzndsk52e2hsj0n23s3uxamev38'

to_satoshis = 1000
t = Transaction(outputs=[Output(to_satoshis, address=to_address)])
transaction_inputs = [
    ('82b8d71924940e66c82ea7f45ab3af9f77e3d51c8b380b7b3352502a924c0290', 0, from_privkey)
]
for ti in transaction_inputs:
    ki = Key(ti[2])
    t.add_input(prev_txid=ti[0], output_n=ti[1], keys=ki.public())

icount = 0
for ti in transaction_inputs:
    ki = Key(ti[2])
    t.sign(ki.private_byte, icount)
    icount += 1

print(t.verify())
rawhextx = t.raw_hex()
print(rawhextx)
srv = Service()
tx = srv.sendrawtransaction(rawhextx)
if tx:
    print("Transaction send, result: ")
    print(srv.results)
    pprint(srv.results)
else:
    print("Transaction could not be send, errors:")
    pprint(srv.errors)
`

And i got this output
`
True
010000000190024c922a5052337b0b388b1cd5e3779fafb35af4a72ec8660e942419d7b882000000006b48304502200876da87e6367a7360ecccbb5aba0c77036178e8ae1b97d96f4959232dec98ea022100f1e94f85b035e631287e101c98e5b55c0d975d370ebf6c365bdb927435be48a8012102142d112dc6e10130986bb4ade787f4c223c9c609c061195bce6c3739ee62c52bffffffff01e803000000000000160014deb6dc6ee88093b14db0b515955e127cd518478600000000
Transaction could not be send, errors:
{'blockchair': 'Error connecting to blockchair on url '
               'https://api.blockchair.com/bitcoin/push/transaction, response '
               '[400] '
               '{"data":null,"context":{"code":400,"source":"R","error":"Invalid '
               'transaction. Error: mandatory-script-verify-flag-failed '
               '(Script failed an OP_EQUALVERIFY '
               'operation)","market_price_usd":39639,"cache":{"live":true,"duration":120,"since":"2022-04-24 '
               '12:08:31","until":"2022-04-24 '
               '12:10:31","time":null},"api":{"version":"2.0.95-ie","last_major_update":"2021-07-19 '
               '00:00:00","next_major_update":null,"documentation":"https:\\/\\/blockchair.com\\/api\\/docs","notice":":)"},"servers":"API4,BTC5","time":0.0007581710815429688,"render_time":0.0016808509826660156,"full_time":0.0024390220642089844,"request_cost":1}}',
 'blocksmurfer': 'Error connecting to blocksmurfer on url '
                 'https://api.blocksmurfer.io/api/v1/btc/transaction_broadcast, '
                 'response [400] {"errors":"Could not send raw transaction. '
                 "b'010000000190024c922a5052337b0b388b1cd5e3779fafb35af4a72ec8660e942419d7b882000000006b48304502200876da87e6367a7360ecccbb5aba0c77036178e8ae1b97d96f4959232dec98ea022100f1e94f85b035e631287e101c98e5b55c0d975d370ebf6c365bdb927435be48a8012102142d112dc6e10130986bb4ade787f4c223c9c609c061195bce6c3739ee62c52bffffffff01e803000000000000160014deb6dc6ee88093b14db0b515955e127cd518478600000000' "
                 'is not JSON '
                 'serializable","raw_response":false,"success":false,"txid":""}\n',
 'blockstream': 'Error connecting to blockstream on url '
                'https://blockstream.info/api/tx, response [400] '
                'sendrawtransaction RPC error: '
                '{"code":-26,"message":"mandatory-script-verify-flag-failed '
                '(Script failed an OP_EQUALVERIFY operation)"}',
 'mempool': 'Error connecting to mempool on url https://mempool.space/api/tx, '
            'response [400] sendrawtransaction RPC error: '
            '{"code":-26,"message":"mandatory-script-verify-flag-failed '
            '(Script failed an OP_EQUALVERIFY operation)"}'}
`

Some more info that i can give, that i know, that if i use something like Wallet() or Key() by passing my priv_key to it, it wrongly determine my wallet address (i.e. like that:
code:
`
key = Key('my_priv_key')
key.address() 
`
output `1KAANCh2PKqcKRCjzavE9gcPsqwLNVjSMW` 
)

I hear something about actual wallet (factual) (maybe it is appear here?), but i anywhere cant find somewhere about that is my wallet (i can't find it in GUI of EXODUS / ELECTRUM)

Yes we get not SegWit format here of wallet, but anyway this is not my wallet, that i get from my (really, tested) private key.

Can you guys help me with something, to solve this problem please!

**Comment by mccwdev** [comment]
Hi,
I saw you already found a solution (https://stackoverflow.com/questions/71652047/how-to-create-and-broadcast-tx-with-multiple-inputs-in-python-bitcoinlib). But yes the output_n refers to the outputs number of the previous transaction.

You can also create an Input objects first and use that to create a transaction.
