### ISSUE TITLE
Balance on wallet instance is not updated when zero

### ISSUE THREAD

**Issue by AbsurdlySuspicious** [1200wd/bitcoinlib#249]
https://github.com/1200wd/bitcoinlib/blob/777e06695cd9d963796afa5ab890e58d140de784/bitcoinlib/wallets.py#L2568-L2582

(function `balance_update_from_serviceprovider`)

When balance is zero this if body is not executed and _balances object is not updated.
This happens for example after `sweep`-ing all funds to another wallet, `scan()` doesn't update balance after this, the only option is to delete wallet instance and re-import it through `Wallet` constructor

**Comment by mccwdev** [comment]
Fixed in https://github.com/1200wd/bitcoinlib/commit/3ea1ace3fdf8da2e39e48348cc660a78e574b6b3
