### ISSUE TITLE
Quest about where wallets are stored?

### ISSUE THREAD

**Issue by stephenoseiowusu** [1200wd/bitcoinlib#251]
I know you can store the wallet keys in a separate database but where is the actual wallet stored ? What size are the wallets created if they are created? Im sorry for asking this simple question but I ask this question on behalf of an organization I cannot name, we should have a crypto expert but we dont and we have to resort to this.... Just my job as a project manager / lead developer.

**Comment by mccwdev** [comment]
The wallets are stored in SQLite format in the user folder in ~/.bitcoinlib/database (on Linux). The size depends on the number of keys and transactions but are usually a few 100Kb's
