### ISSUE TITLE
database feature not needed, helppppp

### ISSUE THREAD

**Issue by Johnnyevans32** [1200wd/bitcoinlib#252]
how can I turn off the database feature of the library, really in love with this library for my app usage buh database feature is a turn off, simply don't want an extra security risk lying around for my users, helppppp

**Comment by mccwdev** [comment]
The database is only used if you work with the Wallet class. If you are just using the Key, Transaction and Service class the database will be created but not used.

**Comment by HexyeDEV** [comment]
would you consider implementing sqlcipher to encrypt the database with a password? I Need to work with the wallet classe but also Need a security layer for the database

**Comment by mccwdev** [comment]
Yes, you can use sqlcipher. See https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.sqlcipher.html
