### ISSUE TITLE
Authproxy default port is 80 irrespective of the url scheme

### ISSUE THREAD

**Issue by merlinmary** [1200wd/bitcoinlib#257]
In Authproxy, if port is not mentioned, the port is set to 80 irrespective of the scheme. It should be 443 for https.

**Comment by merlinmary** [comment]
Fix: https://github.com/1200wd/bitcoinlib/pull/255

**Comment by mccwdev** [comment]
Fixed in 1e41b9bf4fbc9a67b3d23e7fbf75936ad5f6f41b
