### ISSUE TITLE
Limit/offset on transactions query

### ISSUE THREAD

**Issue by oggy95** [1200wd/bitcoinlib#264]
Investigating method wallet.transactions() didn't find parameters for count limit of transactions for wallet.
Is it possible to add in limit/offset for this method?

**Comment by mccwdev** [comment]
The wallet.transaction() method depends on 2 queries so using limit/offset on database level is difficult. 

I was wondering what is you use case?  Maybe it can be solved with using list comprehension?

**Comment by oggy95** [comment]
When this lib using as backend service for some exchange service, load all transactions from database may be long, it can be improved by loading transactions partially (chunks).

**Comment by mccwdev** [comment]
Limit and offset has been added to wallet.transaction_full method, see https://github.com/1200wd/bitcoinlib/commit/d914dde6a98006a0107d8433b7d7044220dd2712
