### ISSUE TITLE
Can't send bitcoin to myself

### ISSUE THREAD

**Issue by crazypon** [1200wd/bitcoinlib#266]
```
def send_to_myself(wallet: Wallet):
    config = configparser.ConfigParser()
    config.read("bot.ini")
    wallet.transactions_update()
    wallet_info = wallet.as_dict()
    main_wallet = config["payments"]["wallet_address"]
    wallet.utxos_update(networks="testnet")
    wallet.balance_update_from_serviceprovider(network="testnet")
    wallet.get_keys()
    wallet.info()
    wallet.scan()
    wallet.transactions_update()
    wallet.transactions_update_confirmations()
    print(wallet.utxos())
    transaction_hash = wallet.send_to(main_wallet, "0.00030000 TBTC", fee=1024)
    print(transaction_hash.info())
    transaction_hash.update_totals()

    return transaction_hash
```
    
    
 **The transaction info() output:**

Transaction fbf725397ecb40474538cca6bc739d8bedb2b87fc77dcd5b08a224be606174ea
Date: None
Network: testnet
Version: 1
Witness type: legacy
Status: new
Verified: True
Inputs
- mi4em68R9HikQsqGEV7svrmRCRbSeKxDmE 0.00030000 tBTC 52d789af2f7372c3fc241ccf6b2c1b0e7ffc765823633ad8939144dbe351f14e 1
  legacy sig_pubkey; sigs: 1 (1-of-1) valid
- mi4em68R9HikQsqGEV7svrmRCRbSeKxDmE 0.00030000 tBTC 914a91dbbe3760bc071ec2292dded28bc7d93f8ac4f566e56e98a9d94d879357 0
  legacy sig_pubkey; sigs: 1 (1-of-1) valid
Outputs
- tb1q30c3c6fe2dtuvewu5x7lus94fhl6kxmsde0yp9 0.00030000 tBTC p2wpkh U
- mgwuvTAQoevZa57wzWQuHb85V1FprMZJVe 0.00028976 tBTC p2pkh U
Size: 370
Vsize: 370
Fee: 1024
Confirmations: None
Block: None
Pushed to network: False
Wallet: 1231974448_7

I have waited some. But nothing happened. Could you help me please?

**Comment by mccwdev** [comment]
You need to push the transaction to the network first. So send it right away with the offline=False parameter, or check it first and then use the send() method.

```
t = wallet.send_to(main_wallet, "0.00030000 TBTC", fee=1024, offline=False)
# or
t.send()
```

**Comment by crazypon** [comment]
@mccwdev Thank you very much!!!
