### ISSUE TITLE
How to get balance of HDKey?

### ISSUE THREAD

**Issue by crazypon** [1200wd/bitcoinlib#268]
```
def generate_new_btc_wallet(user_id: int, wallet_id: Union[float, int]):
    config = configparser.ConfigParser()
    config.read("bot.ini")
    k = HDKey(config["payments"]["wallet_privkey"], network="bitcoin")
    ck = k.child_public(2235, network="bitcoin")
    address = ck.address()
    return address
```
I want to get a balance of HDKey, or get information about transaction using transaction hash. How can I do this?

**Comment by crazypon** [comment]
How can I create HDKey in the testnet network?

**Comment by mccwdev** [comment]
With the Service class you can retrieve transaction, utxo and balance information for a specific address. See documentation at https://bitcoinlib.readthedocs.io/en/latest/source/bitcoinlib.services.services.html#bitcoinlib.services.services.Service

And https://github.com/1200wd/bitcoinlib/blob/master/examples/services.py for some examples
