### ISSUE TITLE
Transaction: one input, several outputs

### ISSUE THREAD

**Issue by Menetar** [1200wd/bitcoinlib#27]
Hey guys,

I was trying to make a transaction from a specific input into several (in this case two) outputs on testnet. I based my procedure on: https://github.com/1200wd/bitcoinlib/blob/abc53591c60f675ec5cc83d9cd62b3ed8cbdd8ef/examples/transactions.py from line 48 to 58.

My code is as follows:

```
inp = Input(prev_hash=i['tx_hash'],output_n=i['output_n'],keys=pubkey.public(), network='testnet')
outputs = []
outputs.append(Output(int(satoshi_amount), address=addr_to, network=network_id))
outputs.append(Output(int(satoshi_amount_2), address=addr_remainder, network=network_id))
t = Transaction(inputs=[inp],outputs=outputs, network=network_id)
t.sign(pubkey.private_byte)

```
And it pops up the following error:

> ERROR: EXCEPTION [<class 'ValueError'>].
> ERROR: [{'bitcoind.testnet': 'Please install bitcoin client and specify a path to config file if path is not default. Or place a config file in .bitcoinlib/config/bitcoin.conf to reference to an external server.'}]

And the second time:

> ERROR: EXCEPTION [<class 'ValueError'>].
> ERROR: [{'chainso.testnet': 'Maximum number of requests reached for chainso with url https://chain.so/api/v2/get_tx_unspent/BTCTEST/n4NwqjtPk54gQUiATsxJ7iyGVxSc99tK6c, response [429] Too many requests. Please try again later, or contact support@block.io for more info.', 'bitcoind.testnet': 'Please install bitcoin client and specify a path to config file if path is not default. Or place a config file in .bitcoinlib/config/bitcoin.conf to reference to an external server.'}]

Do you have any idea why this is? I have no problem executing the transaction to a single address, but I'm having a hard time splitting it into two.

Thank you for your time,

Menetar

**Comment by mccwdev** [comment]
Hi Menetar,
In your code you create and sign a transaction and this looks OK.
But the errors are about requests to Service providers about unspent outputs, so they have to be caused by other code. These service errors shouldn't cause any problems btw: if chain.so received to many requests, bitcoind just tries another provider.
Best regards,
Lennart

**Comment by Menetar** [comment]
Hi mccwdev,
Thank you for your answer. I'll take a deeper look into there rest of the code to see where the error is! As long as the transaction is well built I can discard it and take a look at everything else.
