### ISSUE TITLE
error transaction 

### ISSUE THREAD

**Issue by Shantaramm** [1200wd/bitcoinlib#272]
I insert output_n, such as it is necessary, I indicate all the necessary information.
The transaction does not go through, what did I do wrong?

```
from bitcoinlib.keys import Key
from bitcoinlib.services.services import Service
from bitcoinlib.transactions import Transaction

k = Key("wif", network="testnet")

srv = Service(network="testnet")

print(srv.getutxos("mjBQGdooSmck8M2kcWHphTMPaxxm1HLA5V"))

txid = "086f43a299e00496a3717dd63cee92a77a3a367e76c05651dc1cbd8b420b16a9"

t = Transaction(network="testnet")

t.add_input(txid, 1)
t.add_output(10000, "mgM5Sg4cXYT9GzYK9RVyMkKhzzSxEw3Gtp")
t.sign(k)
tx = Service(network="testnet").sendrawtransaction(t.raw_hex())
print(t.verify())
print(tx)
```

![изображение](https://user-images.githubusercontent.com/56877750/201536238-65801d02-9233-442c-bc23-fddae777708e.png)

**Comment by mccwdev** [comment]
Could you check in the logs, too see if there are any specific provider errors?
Are you using the latest version? And are you sure the fees is sufficient and the outputs unspent?

**Comment by Shantaramm** [comment]
> Could you check in the logs, too see if there are any specific provider errors? Are you using the latest version? And are you sure the fees is sufficient and the outputs unspent?

And what should be done to check if the transaction was spent? I used the send_to() method, where I did not choose which transaction to take from utxo. How to make send_to not take spent transactions? (issue 274)

**Comment by Shantaramm** [comment]
And one more question, when I send a transaction using the send / send_to method, from the wallet, how can I specify the change address? :)

**Comment by mccwdev** [comment]
With a Wallet object you can just use the scan(), utxos_update() method to get the unspent outputs. If you create a Transaction object yourself you use the Service.getutxos() like in the example above. It could be that there is some problem with the service providers or a mismatch of keys/utxos. If you could send me the complete code and outputs in the logs I can take a look into it.

The Wallet.send() method pick the next available unused change_address from the wallet. However if you specify a complete output_arr and fee which adds up as the same amounts of the total of the inputs, then no change output is generated. So you specify the change output yourself.

**Comment by Shantaramm** [comment]
> 
I figured out the first one, it was my mistake, I sent transactions with a small commission, so utxo were involved, but not spent, since the transaction was not confirmed.
Thank you!

Regarding the second question, should I just specify the second output as: [(addr, amount), (addr_change, amount_imput-amount-fee)]?

**Comment by Shantaramm** [comment]
P.s And I also wanted to say that litecoin_testnet service providers do not behave correctly, or maybe I'm doing something wrong, there are no such problems with other networks.

![изображение](https://user-images.githubusercontent.com/56877750/202430857-09b0062f-3b02-4135-93a7-aa10ac9e73be.png)

**Comment by mccwdev** [comment]
> Regarding the second question, should I just specify the second output as: [(addr, amount), (addr_change, amount_imput-amount-fee)]?

Yes correct


At the moment only bitaps and chain.so offer a litecoin_testnet api, and both providers do not have fee estimation data. So unfortunately the only workaround would be to install a litecoin testnet node locally.

**Comment by Shantaramm** [comment]
> 

Okay, thanks for the replies!

**Comment by Shantaramm** [comment]
> 

And I also wanted to ask) When I do srv.getutxo(addr), the director sometimes returns outdated information or an empty array to me, can this only happen in the testnet or is it also possible in the normal litecoin / bitcoin network?

**Comment by mccwdev** [comment]
That fee should be sufficient.  The getutxos() method depends on external service providers, if they return incorrect or incomplete results, the method does as well.  Please check the logs and let me know which provider causes this issue, to see if it fixable.

**Comment by Shantaramm** [comment]
Okay thanks! Can you tell me how I can check the logs?

**Comment by mccwdev** [comment]
You can find the logs in ./bitcoinlib/bitoinlib.log in your user directory
