### ISSUE TITLE
HDKey sign 

### ISSUE THREAD

**Issue by Shantaramm** [1200wd/bitcoinlib#275]
![изображение](https://user-images.githubusercontent.com/56877750/203144423-09d8bee7-faa2-4167-85e8-0d05f4a2775c.png)

I have HDKey and I want to use it to sign a transaction

![изображение](https://user-images.githubusercontent.com/56877750/203144728-f908471d-23b5-41ea-83eb-385bb8922587.png)

But I keep getting this error(There is no problem with regular Key()):

![изображение](https://user-images.githubusercontent.com/56877750/203144936-1b848a71-e37e-471e-a71e-418c0dfe065c.png)

I will be grateful for your help!

**Comment by mccwdev** [comment]
Please check if key is the same and private. And I think it is necessary to provide key in add_input.

See an example in https://github.com/1200wd/bitcoinlib/blob/4431f1a3f361119e9552814fd4fffe47fac75680/tests/test_transactions.py#L257

**Comment by Shantaramm** [comment]
> I checked, everything seems to be correct, I tried to change the HDKey (what I substitute as the first argument is wif, right?), I added k.public () to add_input. Still the same error

**Comment by Shantaramm** [comment]
![изображение](https://user-images.githubusercontent.com/56877750/203402058-fb8aade7-d917-4c7f-8665-cb2d136d360d.png)

it defines the segwit address as p2wpkh, can there be an error because of this?

**Comment by mccwdev** [comment]
This worked for me, I think you also have the mention the 'witness_type' when creating a transaction / input.

```
pk = 'vprv9DMUxX4ShgxMMYGrjFHRaGV9CvX3uajhQKXo3DJK3tHb1JbwrPZNWPdN8JWoVQYU41hWFF3WMwoA5ERq346VyPssA5okR5iczwsfPTFxNqP'
k = HDKey(pk)

fee = 500
value = 0
addr_to = 'tb1q4280xax2lt0u5a5s9hd4easuvzalm8v9ege9ge'

utxos = Service(network='testnet').getutxos(k.address())
t = Transaction(network='testnet', fee=fee, witness_type='segwit')
for utxo in utxos:
    t.add_input(utxo['txid'], utxo['output_n'], value=utxo['value'], witness_type='segwit')
    value += utxo['value']
t.add_output(value-fee, addr_to)
t.sign(k)
t.verify()
t.info()
Service(network='testnet').sendrawtransaction(t.raw_hex())
```

**Comment by Shantaramm** [comment]
Now I'm trying to send a transaction on the Litecoin network, I'm getting errors, do I need to install these packages?

![изображение](https://user-images.githubusercontent.com/56877750/204639318-f08f7fec-a842-4b27-a125-2483389e14a6.png)

**Comment by mccwdev** [comment]
It would be better to install the scrypt module, but I assume this is not the cause of these errors.

If you set the loglevel to DEBUG in .bitcoinlib/config.ini you can get more information why those three providers returned an error.

**Comment by mccwdev** [comment]
Changing loglevel to DEBUG should give loads of debug messages, are you sure you changed the correct config.ini and it contains only one line with
`loglevel=DEBUG`

**Comment by Shantaramm** [comment]
> I already figured everything out, thank you very much!!!

**Comment by Shantaramm** [comment]
> Changing loglevel to DEBUG should give loads of debug messages, are you sure you changed the correct config.ini and it contains only one line with `loglevel=DEBUG`

I already figured everything out, thank you very much!!!

**Comment by Catchii69** [comment]
> > Changing loglevel to DEBUG should give loads of debug messages, are you sure you changed the correct config.ini and it contains only one line with `loglevel=DEBUG`
> 
> I already figured everything out, thank you very much!!!

hey im having the same problem, could you maybe share your code?

**Comment by Shantaramm** [comment]
> > > Changing loglevel to DEBUG should give loads of debug messages, are you sure you changed the correct config.ini and it contains only one line with `loglevel=DEBUG`
> > 
> > 
> > I already figured everything out, thank you very much!!!
> 
> hey im having the same problem, could you maybe share your code?

Hi, what exactly is your problem?

**Comment by Catchii69** [comment]
> > > > Changing loglevel to DEBUG should give loads of debug messages, are you sure you changed the correct config.ini and it contains only one line with `loglevel=DEBUG`
> 
> > > 
> 
> > > 
> 
> > > I already figured everything out, thank you very much!!!
> 
> > 
> 
> > hey im having the same problem, could you maybe share your code?
> 
> 
> 
> Hi, what exactly is your problem?

My transaction won't send even tho I sign it etc... won't push to the blockchain, no errors in logs

**Comment by Shantaramm** [comment]
> > > > > Changing loglevel to DEBUG should give loads of debug messages, are you sure you changed the correct config.ini and it contains only one line with `loglevel=DEBUG`
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I already figured everything out, thank you very much!!!
> > 
> > 
> > > 
> > 
> > 
> > > hey im having the same problem, could you maybe share your code?
> > 
> > 
> > Hi, what exactly is your problem?
> 
> My transaction won't send even tho I sign it etc... won't push to the blockchain, no errors in logs

I had this initially, I then put too little commission.

When I had a problem with segwit addresses, I did everything mccwdev said and it worked!

![изображение](https://user-images.githubusercontent.com/56877750/206904506-a43dc756-7de0-499e-b7da-4329d48e593e.png)

here you need to explicitly indicate in the withnes_type transaction that the transaction comes from the segwit address, and specify the sigwit address in the transaction inputs

**Comment by Catchii69** [comment]
```
     pk = w1.wif()
     k = HDKey(pk, network=NETWORK)
     fee = 12500
     value = 650634
     addr_to = 'LUm3rxLbwTFNzNrgKZQXNYSCt6ybNNMiCQ'

     utxos = Service(network='litecoin').getutxos(k.address())
     t = Transaction(network='litecoin', fee=fee, witness_type='segwit')
     for utxo in utxos:
         t.add_input(utxo['txid'], utxo['output_n'], value=utxo['value'], witness_type='segwit')
         value += utxo['value']
     t.add_output(value - fee, addr_to)
     t.sign(pk)
     t.verify()
     t.info()
     print(t.raw)
     Service(network='litecoin').sendrawtransaction(t.raw_hex())
```
this is my code and it wont send for some reason...

**Comment by Catchii69** [comment]
> Now I'm trying to send a transaction on the Litecoin network, I'm getting errors, do I need to install these packages?
> 
> ![изображение](https://user-images.githubusercontent.com/56877750/204639318-f08f7fec-a842-4b27-a125-2483389e14a6.png)

this is the exact problem i have

**Comment by mccwdev** [comment]
Your code seems correct, you could try to pass the private key in another format or specify the witness format:

`      k = HDKey(pk, network=NETWORK, witness_type='segwit')
`

The transactions is refused by 3 providers, if you change the log level to debug (see above) you can get more specific warnings from the providers.

**Comment by Catchii69** [comment]
> 

does not work either...

**Comment by Shantaramm** [comment]
> > 
> 
> does not work either...
Perhaps your commission is too small, 12500 litoshi for litecoin, as for me it’s not enough, I bet 100000

**Comment by Shantaramm** [comment]
> > 
> 
> does not work either...

 Perhaps your commission is too small, 12500 litoshi for litecoin, as for me it’s not enough, I bet 100000

**Comment by mccwdev** [comment]
Could be related to https://github.com/1200wd/bitcoinlib/issues/278

If you get different errors, please post logs results from providers

**Comment by Catchii69** [comment]
still does sadly not work,

logs are
```
2022/12/14 13:54:00 WARNING <module>(72) Could not include fastecdsa library, using slower ecdsa instead.
2022/12/14 13:54:05 WARNING _provider_execute(213) Aborting, max errors exceeded: ['litecoinblockexplorer.litecoin', 'blockchair.litecoin', 'blockcypher.litecoin']
```

my code is
```
NETWORK = 'litecoin'
wallet = Wallet('myw2a23d4413let')
wif = wallet.wif()
print(wallet.balance())

k = HDKey(wif, network=NETWORK, witness_type='segwit')

fee = 100000
value = 600000
addr_to = 'ltc1qvjc407rtukknelqs85ze3uumc22waevdftklzs'


utxos = Service(network='litecoin').getutxos(k.address())
t = Transaction(network='litecoin', fee=fee, witness_type='segwit')
for utxo in utxos:
    t.add_input(utxo['txid'], utxo['output_n'], value=utxo['value'], witness_type='segwit')
    value += utxo['value']
t.add_output(value - fee, addr_to)
t.sign(wif)
t.verify()
t.info()
print(t.raw)
Service(network='litecoin').sendrawtransaction(t.raw_hex())
```

**Comment by Shantaramm** [comment]
> 

Perhaps your balance does not have enough funds, since you add to your 600000 value, another value of unspent transactions and as a result you indicate an amount much larger than the amount you have, the decision is to make value = 0, and then in the for loop do += utxo['value']

**Comment by superggn** [comment]
it seems the `HDKey` has `bitcoin seed` hardcoded in the function? maybe that's the issue?

**Comment by mccwdev** [comment]
The hardcoded 'bitcoin seed' as salt is intented and defined in BIP0032 https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

**Comment by superggn** [comment]
thanks, that solves my confuse, I thought `if bitcoin seed is hard coded then the lib would not support altcoins` before, I'm happy I was wrong
