### ISSUE TITLE
Documentation readthedocs - incorrect path to providers.json

### ISSUE THREAD

**Issue by Nine-Black** [1200wd/bitcoinlib#276]
Following information in [documentation](https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.install.html#tweak-bitcoinlib) :

> Some service providers require an API key to function or allow additional requests. You can add this key to the provider settings file in .bitcoinlib/providers.json

Correct path to file is .bitcoinlib/**data**/providers.json

**Comment by mccwdev** [comment]
Hi,
There is no data directory in the latest versions of Bitcoinlib, so the link seems correct
