### ISSUE TITLE
bcoin.py Exception on len(utxo)<50

### ISSUE THREAD

**Issue by siahlooei** [1200wd/bitcoinlib#282]
Hi

Check this code of bcoin.py.

https://github.com/1200wd/bitcoinlib/blob/cb0823bc41a08743dcb2ba3cfa4f949bb0b232f9/bitcoinlib/services/bcoin.py#L90-L97

I think this condition is not correct.
The "not" is in the condition (line 96) is wrong.

I  suppose a fix: 
Rewrite this condition with
"
if len(txs) > 50:
"

This fix can resolve the problem.

**Comment by mccwdev** [comment]
Not sure how 'not' ended up there, but thanks for the fix!
