### ISSUE TITLE
Testnet balance

### ISSUE THREAD

**Issue by HexyeDEV** [1200wd/bitcoinlib#286]
I tried making a wallet on both litecoin testnet and Bitcoin testnet, After sending funds to those and waiting for the transactions to confirm, I tried to call wallet.balance() and It still returned 0 and also wallet.info() do not show any transaction, this Is probably an error on my end, could you help me?

**Comment by HexyeDEV** [comment]
*also only Bitcoin testnet returned the exception no unspent utxo found when trying to make a transaction, litecoin testnet returned that no porvider returned a good response

**Comment by HexyeDEV** [comment]
I realized I wasn't calling wallet.scan() but the problem with litecoin testnet Is still there

**Comment by mccwdev** [comment]
Litecoin testnet is not supported by a lot of API providers anymore. You could try to request an API key at chain.so, or run a litecoin testnet server locally.
