### ISSUE TITLE
No successful response from any serviceprovider: ['bitaps.litecoin.testnet', 'chainso.litecoin.testnet']

### ISSUE THREAD

**Issue by tomjeannesson** [1200wd/bitcoinlib#287]
I am getting the following error: `bitcoinlib.services.services.ServiceError: No successful response from any serviceprovider: ['bitaps.litecoin.testnet', 'chainso.litecoin.testnet']` when trying to call `wallet.utxos_update()` or `wallet.transactions_update()`.

Here is a code snippet to reproduce:
```
from bitcoinlib.wallets import Wallet
wallet = Wallet.create(
    name=f"Wallet",
    network="litecoin_testnet",
)
wallet.utxos_update()
wallet.transactions_update()
```
Any ideas on how to fix this?

**Comment by tomjeannesson** [comment]
It seams to me the correct endpoint for `bitaps.litecoin.testnet` is `https://api.bitaps.com/ltc/testnet/v1/blockchain/address/transactions/{address}`. Any ideas on how to change this?
For `chainso.litecoin.testnet`, they seem to be behind a paywall.

**Comment by mccwdev** [comment]
Bitaps seems to be the only Litecoin Testnet provider still available, but that one works only partial. I Could no find any other free providers, may someone has a suggestion?

**Comment by shahverd** [comment]
I'm facing the same problem with bitcoin testnet. And it happens when update UTXOs.

**Comment by mccwdev** [comment]
Are you using the latest version? I did some fixes recently.
And could you check the logs, to see what specific error occur?

**Comment by shahverd** [comment]
I wasn't using the laster version, so I updated it, and now it seems that everything is working again. 
thanks
