### ISSUE TITLE
Litecoin wallet restoration

### ISSUE THREAD

**Issue by superggn** [1200wd/bitcoinlib#297]
Hi there, I ran into an issue with restoring the litecoin testnet wallet with bitcoinlib...
At first I thought there should be a way using the mnemonics for restoration, but can't find one.
Then I tried using the hdkey by adding the master seed generated via bip_utils, but still not working, cause it seems "bitcoin seed" is hardcoded into this lib...

So is there any other way I can restore an altcoin wallet?

Best regards

**Comment by superggn** [comment]
key word for searching: litecoin, litecoin testnet, altcoin, dogecoin, dogecoin testnet

**Comment by mccwdev** [comment]
The library follows the BIP0032 standard, so that is why the 'bitcoin seed' salt is hardcoded.

Can you explain what issues you encounter when trying to create a wallet from a mnemonic key?

**Comment by superggn** [comment]
I checked my code again, turns out that I misconfigured the path, I used "m/44'/0'/0'/0/0" instead of "m/44'/1'/0'/0/0"...

my original problem:
the wallet I restored using bitcoinlib is not generating the same key under the same path as using bip_utils

**Comment by superggn** [comment]
code that works:
```
NETWORK = 'litecoin_testnet'
mnemonic_str = 'Hi there this is my mnemonic string ...'
k = HDKey.from_passphrase(mnemonic_str, network=NETWORK)
# working wallet
wallet_test_restore = Wallet.create(
    name="Wallet_test_restore",
    keys=k,
    network=NETWORK,
)
# path: meaning derivation path
target_address = wallet_test_restore.key_for_path("m/44'/1'/0'/0/0")
```

**Comment by superggn** [comment]
ahhh.... I was using this:
```
hdkey = HDKey.from_seed(master_seed_hex, NETWORK)
```
not this:
```
hdkey = HDKey.from_seed(master_seed_hex, network=NETWORK)
```
and the second param is not network.... sad
