### ISSUE TITLE
Transaction.create() fails for non-bitcoin transactions?

### ISSUE THREAD

**Issue by mkiesel** [1200wd/bitcoinlib#30]
https://github.com/1200wd/bitcoinlib/blob/722916f01b92afe981ce18de54f6017c0e240db9/bitcoinlib/wallets.py#L2513 fetches/recreates a HDKey instance but fails to pass the network type to it. Not sure if the current version of the library still has a problem with that, but at least the current pip version complained with `WalletError: Created input address is different from address of used key. Possibly wrong key order in multisig?` after that because addresses of the keys wouldn't match later.

Fix:
> inp_keys = HDKey(key.wif, compressed=key.compressed, **network=key.network_name**).key

**Comment by mccwdev** [comment]
Thanks, will take a look at it. This issue with HDKey without network probably occurs at other places too.

**Comment by mccwdev** [comment]
Fixed in https://github.com/1200wd/bitcoinlib/pull/32
