### ISSUE TITLE
How to protect the wallets

### ISSUE THREAD

**Issue by x011** [1200wd/bitcoinlib#300]
Hi,
I couldn't find a way to  protect/encrypt the wallet/database on windows. 
`pip install sqlcipher3-binary`
returns:
`ERROR: No matching distribution found for sqlcipher3-binary`

How can I protect/encrypt the sqlite database so other person cannot use it without a password?
I'm asking this because (I think) that anyone with access to the same computer can send transactions. 
Is this a correct assumption? If so, how can this be avoided?

**Comment by shahverd** [comment]
Any offline solutions like single password mechanism is useless. That's why most SQLite implementations doesn't come with encryption by default.

**Comment by superggn** [comment]
I think offline management is secure enough?
Say the main cold wallet is always offline, only keep a small amount of cash in the hot wallet online, I think that's a secure way.
I thinks there should only the admin can have the access to the computer signing transaction, and the computer signing the transaction and sending the transaction can be different computers.
Lets say computer A sign the transaction, and computer B sends the transaction. A send the signed transaction to B, and B broadcast the transaction to the blockchain. So there can be 2 computers.

**Comment by superggn** [comment]
If you use the kubernetes to manage your system, there're rbac and abac which can implement the access control, also a secure way

**Comment by mccwdev** [comment]
There are several ways to protect your wallet, one of the safest is to use an offline wallet as @superggn suggested.

Some others ways are:
* Use a password protected passphrase
https://github.com/1200wd/bitcoinlib/blob/a61f490f5ac4c043af01b502d0df43b2c49af7a9/examples/wallets_mnemonic.py#L24-L29
* Encrypt private keys fields: 
https://github.com/1200wd/bitcoinlib/blob/master/examples/database_encrypted.py
* Encrypt database using sqlcipher: https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.sqlcipher.html   Not sure how to get this working in Windows, maybe you can find / ask it here: https://github.com/coleifer/sqlcipher3

The general documentation, but needs to be updated:
https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.security.html
