### ISSUE TITLE
Litecoin multi wallet send

### ISSUE THREAD

**Issue by steveboy199** [1200wd/bitcoinlib#302]
Hello, whenever I send from one wallet to many wallets using this library under the litecoin network it always clears out my entire wallet. I even specify the fee. I have lost around $20 from this. I believe I am doing something wrong. I do specify the fee and if I dont the documentation says it would provide one for me.

amount = 20000000 * 0.90
fee = 20000000 * 0.05
w.send([('MHoNyWp36xPN63Pbz53qVinat5jCHebyub', amount),('MHoNyWp36xPN63Pbz53qVinat5jCHebyub', amount),('MHoNyWp36xPN63Pbz53qVinat5jCHebyub', amount)], offline=false, fee=fee)

thats just an example above. Instead of abiding by the fee, it instead clears my entire wallet balance sending the right amount to the wallets specified but the rest of the wallet amount goes toward the transaction fee. What am I doing wrong, examples would be helpful. This functionality is for a small app.

Also the changes reflect on the litecoin block chain however whenever I update the unspent transactions by calling wallet.update_utxos() it reflects as if the wallets balance is still there but when I put the wallet address in a blockchain  explorer it says a significant amount went to the miner like 90% of the wallet.

heres the blockchain summary of the transaction  https://blockchair.com/litecoin/address/LMA9BZcYR1cBMytmZgHR4UcQhPeD2qhAQM

**Comment by stephenoseiowusu** [comment]
Never mind I found the other litecoin, it was in the other addresses tied to the wallet.

**Comment by steveboy199** [comment]
I  found where the litecoin is. It was in the other addresses tied to my wallet

**Comment by mccwdev** [comment]
To debug and test you can use the Wallet.info() method. This prints all wallet keys, transactions and balance to standard output.
