### ISSUE TITLE
ERROR: Failed building wheel for fastecdsa

### ISSUE THREAD

**Issue by StasFQ** [1200wd/bitcoinlib#305]
While I'm trying to install this lib, I got this error.MacOS, M1

In file included from src/curve.c:1:
  src/curve.h:4:10: fatal error: 'gmp.h' file not found
  #include "gmp.h"
           ^~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for fastecdsa

**Comment by tanguynicolas** [comment]
Same on Debian 11 with Python 3.9.2

**Comment by mccwdev** [comment]
You need to install the GMP library dependencies:

`apt install build-essential python3-dev libgmp3-dev`

More info can be found here: https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.install.html
and here: https://github.com/AntonKueltz/fastecdsa#installing

**Comment by mccwdev** [comment]
Moved to discussions: https://github.com/1200wd/bitcoinlib/discussions/306
