### ISSUE TITLE
Litecoin (Mainnet) Transaction Parse Error

### ISSUE THREAD

**Issue by superggn** [1200wd/bitcoinlib#310]
Hi there~ I'm using the following config to connect to litecoin mainnet
```
# insert this into bitcoinlib/data/providers.json
  "litecoin": {
    "provider": "litecoind",
    "network": "litecoin",
    "client_class": "LitecoindClient",
    "provider_coin_id": "",
    "url": "https://ltc.getblock.io/39e5b219-1c6f-4ad2-8a59-9484c314c782/mainnet/",
    "api_key": "",
    "priority": 10,
    "denominator": 100000000,
    "network_overrides": null
  },
```
```python3
connection_obj = Service(network=NETWORK)
t = connection_obj.gettransaction('146647773f600724ca695ac68d1dd10843a9f23bc0580b1537d8e490fdce44fc')
raw_t = connection_obj.getrawtransaction('146647773f600724ca695ac68d1dd10843a9f23bc0580b1537d8e490fdce44fc')
print('t.outputs', t.outputs)
print('t.outputs[0]', t.outputs[0])
```
now the output address is different from what we can see in the browser (https://chain.so/tx/LTC/146647773f600724ca695ac68d1dd10843a9f23bc0580b1537d8e490fdce44fc)

my output address is 'ltc1p8ln7cusk707t0dzt6kqrewxkeek0anujhfu5g0rq60sa6fwv30msxrttj3', while from browser we can see the output address is 'ltc1g8ln7cusk707t0dzt6kqrewxkeek0anujhfu5g0rq60sa6fwv30mshzk03f'

<img width="1078" alt="image" src="https://github.com/1200wd/bitcoinlib/assets/26425769/f8f15f26-2e36-43a9-85a6-2901c47d0ee1">

<img width="784" alt="image" src="https://github.com/1200wd/bitcoinlib/assets/26425769/199f3832-bfaa-4702-bcc4-8a61b1c78471">

and I checked about 10+ blocks manually, found that the wrongly parsed addresses are all p2tr, but I cannot ruleout the possibility that other addresses being wrongly parsed.

**Comment by superggn** [comment]
let me add a little more detail:
when the output is multiple (contain p2wpkh address), then the parsing could be correct (see https://chain.so/tx/LTC/5965813e1a9958458c0cce9ae7a7cd099e8c40ab6a1a1ea26252d92927aa06c7)
but when the output is singular, then parsing is wrong (see https://chain.so/tx/LTC/19b7ad5a1e9e9418bf6ff50f220bfcd0bbce1be0e06449d3890871d287c8ef01)

**Comment by mccwdev** [comment]
It seems Litecoin uses 8 as witness version for the p2tr address instead of 1. I'm not sure if that is always the case and if there is any consensus about this.

Blockchair shows other addresses but those seem just incorrect.

Anyway this is a quick and dirty fix, seems to work for the transactions I have seen so far: 5f076cc847bf4909592f36745f1c63a815bf14b9

**Comment by superggn** [comment]
Huge Thanks! I tried it and it works perfectly!
