### ISSUE TITLE
Transaction error

### ISSUE THREAD

**Issue by HexyeDEV** [1200wd/bitcoinlib#319]
When creating a transaction with multiple inputs, 1 of the 2 inputs (which are both tx ids) is not in the UTXO list even if when printing the UTXOs the transaction actually appears. Looking further I can see that the unrecognised transaction has 0 as output_n even if the transaction actually has 2 outputs. I am using the litecoin network and the transaction is 83281cce8a14e0eecbb42ce5aa63c42ccf29e95f492cf4c1ec7c0356f5d7bc64

**Comment by mccwdev** [comment]
Could you share the code which leads to this error and the exact error you receive?

**Comment by HexyeDEV** [comment]
I just realized I was

**Comment by HexyeDEV** [comment]
*I was inputting the total number of outputs instead of the output to be sent
