### ISSUE TITLE
resend non confirmed bitcoins?

### ISSUE THREAD

**Issue by pixel-wipe** [1200wd/bitcoinlib#321]
Hello guys!

i has interesting question and interesting trouble.

~45 days ago i has send all my bitcoins(there was be ~400 bucks in bitcoins balanced at legacy wallet) to new address
i has put fee as ~2 satoshi per byte.

this tx still has no confirmations yet.
i has rebroadcast it few times with free services... and even paid some scam service to accelerate it lol! (has lost 20 bucks)

this tx has signed ~300 inputs as outputs so in total fee was around 25 bucks (mass amount of signed data)

this tx was been done from wallet that has no RBF options. so iam stuck and freeze with my tx.

is it possible to manually do new tx that will resend all my bitcoins with more fee? (~5 will be good anought at this moment i think)

all tools that i has to try before always showed up that my wallet has zero balance while my full-amount out_tx still has 0 confirmations.
does i correctly understand that if i will do that i has asked before - my new tx with higher fee will be early accepted and confirmed by miners. and i will solve my trouble this way?

**Comment by mccwdev** [comment]
Yes, you can send a new transaction with higher fees and hope it will replace the old transaction, eventually this will succeed, but it can take several weeks.

Another method is to create a [Child pays for parent (CPFP)](https://bitcoinops.org/en/topics/cpfp/) transaction. A new transaction which spends the output from the stuck transaction but with higher fees so the miners will include your transaction in a new block.
