### ISSUE TITLE
Up to date advice on db encryption?

### ISSUE THREAD

**Issue by sjeohp** [1200wd/bitcoinlib#327]
Since pysqlcipher does not appear to be maintained any longer, is there any advice on using encrypted databases?

**Comment by sjeohp** [comment]
I am unable to get it working with sqlcipher3 on macos 13.

**Comment by mccwdev** [comment]
You should usesqlcipher3-binary library instead

Please check https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.sqlcipher.html
