### ISSUE TITLE
Wallet not found, passphrase error

### ISSUE THREAD

**Issue by StasFQ** [1200wd/bitcoinlib#328]
I am using docker for my project and database, volumes are configured correctly.When I do a re-build of the image(update to code)
I get an error:
 bitcoinlib.wallets.WalletError: Wallet 'wallet_name' not found, please specify correct wallet ID or name.
 Then got this:
 PassphraseError: Wrong passphrase
 How to fix that?

**Comment by mccwdev** [comment]
Not sure, looks like the database or link to the database is different. Please check the link to database and make sure the database is not overwritten during an image rebuild.

**Comment by StasFQ** [comment]
No, the database is not overwritten when the image is rebuilt, the problem is only with bitcoin and Litecoin wallets,everything else works successfully in the project

**Comment by mccwdev** [comment]
It's hard to tell why the wallet cannot be found without knowing the details of your project.
Maybe you can check with list_wallets() if the wallet is available in the database, or try to open it with the id instead of the name.

**Comment by StasFQ** [comment]
resolved with db_uri
