### ISSUE TITLE
Getting getutxos confirmations and balance of an address

### ISSUE THREAD

**Issue by Menetar** [1200wd/bitcoinlib#33]
Hi guys,

I'm currently reading the utxo of an address to check if I can consider a transaction to have the 6 recommended confirmations. But I have noticed that several times the amount of confirmations tend to go back, even as much as 3 confirmations. I was wondering if there have been an issue found or it might be regarding the provider. 
Same thing happens, it seems, with getting the balance. 
The methods are .getbalance and .getutxos.
(using version 0.3.33a2)
Thanks!

**Comment by mccwdev** [comment]
I recently fixed some UTXO update issues, can you try it with the latest version (0.3.34), this should fix this I assume.
