### ISSUE TITLE
Error in parsing one specific transaction only (edge case?)

### ISSUE THREAD

**Issue by pputnik** [1200wd/bitcoinlib#338]
Hello,
I'm using `Service.gettransaction(txid)` to get a lot of transactions and found one which the library fails to process properly.

Way to test:

```
from bitcoinlib.services.services import *

srv = Service(network='bitcoin')
txid = "a618dc10b8a1f9d9a1469b3bb84fc17da86df2d51c27e2aa16fa130953840735"
print(srv.gettransaction(txid))   # <=== here returns False
```

I've traced the flow to `/bitcoinlib/scripts.py`:

```
class Script(object):
    def parse_bytesio(...):
         (...)
                if data_type == 'signature':
                    try:
                        sig = Signature.parse_bytes(data)
                        signatures.append(sig)
                        hash_type = sig.hash_type
                        blueprint.append('signature')
                    except Exception as e:
                       # ====== > Here `e` is "Expected a sequence of 69 bytes, got 70"
                        (...)
```
As far as I see [here](https://www.blockchain.com/explorer/transactions/btc/a618dc10b8a1f9d9a1469b3bb84fc17da86df2d51c27e2aa16fa130953840735) this transaction looks quite valid.
Could you help, please?

Python 3.11.4
bitcoinlib         0.6.12

**Comment by mccwdev** [comment]
This transaction contains a non-standard signature, which Bitcoinlib cannot parse. The signature contains an extra byte and is considered invalid with current standards. See https://github.com/bitcoin/bips/blob/master/bip-0066.mediawiki

You can use the strict=False setting to avoid raising errors and continue parsing the rest of the transaction.

**Comment by pputnik** [comment]
Hello,
Similar error using `BitcoindClient` instead of `Service`:
```
from bitcoinlib.services.bitcoind import *

bdc = BitcoindClient.from_config('/path/to/bitcoin.conf')
txid = "67e758b27df26ad609f943b30e5bbb270d835b737c8b3df1a7944ba08df8b9a2"
t = bdc.gettransaction(txid)

print(t.as_json())
```

The error:

```
    self.script = Script.parse_bytes(self.unlocking_script, strict=strict)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/bitcoinlib/scripts.py", line 492, in parse_bytes
    return cls.parse_bytesio(BytesIO(script), message, tx_data, data_length, strict, _level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/bitcoinlib/scripts.py", line 351, in parse_bytesio
    raise ScriptError(str(e))
bitcoinlib.scripts.ScriptError: Expected a sequence of 69 bytes, got 70

```

I tried 
```
bdc = BitcoindClient.from_config('/path/to/bitcoin.conf', strict=False)
```
but got error 
`TypeError: BitcoindClient.from_config() got an unexpected keyword argument 'strict'`

Could you please lmk what is the workaround for this case?
