### ISSUE TITLE
How to create OP_RETURN transaction

### ISSUE THREAD

**Issue by youmark** [1200wd/bitcoinlib#34]
I read the code, there is 'nulldata' script type defined in transactions.py, but could not find how to use it to create a OP_RETURN transaction. Please advise.

**Comment by mccwdev** [comment]
You can find an example at http://coineva.com/use-nulldata-to-send-blockchain-messages.html
Basically you just add an OP_RETURN character to the output lock script.

**Comment by youmark** [comment]
Works like a charm. Thanks for the example.
