### ISSUE TITLE
OSError: Locale is currently set to 'utf-8'. This library needs the locale set to UTF-8 to function properly

### ISSUE THREAD

**Issue by dwjorgeb** [1200wd/bitcoinlib#343]
> OSError: Locale is currently set to 'utf-8'. This library needs the locale set to UTF-8 to function properly

`bitcoinlib/config/config.py` L126:
```python
elif locale.getpreferredencoding() != 'UTF-8':
    raise EnvironmentError("Locale is currently set to '%s'. "
                           "This library needs the locale set to UTF-8 to function properly" %
                           locale.getpreferredencoding())
```

This check should be case-insensitive, it is error-ing out on `Python >=3.11`, as `locale.getpreferredencoding()` changed from returning `UTF-8` to `utf-8`

https://docs.python.org/3.11/library/locale.html#locale.getpreferredencoding

**Comment by mccwdev** [comment]
Fixed in commit 6c82ac40ac66cfec2fd010d7bbcf70d5df46e623

Also updated documentation. It is recommended to use Python in utf-8 mode when using this library:
https://docs.python.org/3/using/windows.html#win-utf8-mode
