### ISSUE TITLE
how to get taproot address from singlekey?

### ISSUE THREAD

**Issue by iteh3712198** [1200wd/bitcoinlib#348]
I'm tring to use this code to get a taproot address , but the result I got is different from the address displayed in my unisat wallet.
`Address(key.public_hex, script_type='p2tr', encoding='bech32').address`

**Comment by iteh3712198** [comment]
> Please check if the unisat wallet is not using a different key path.
> 
> And I think it should be like this:
> 
> ```python
>  addr = Address(hashed_data=key.hash160, script_type='p2tr', encoding='bech32').address
> ```

I used this method, but the address I got was inconsistent with the address shown in my wallet

**Comment by mccwdev** [comment]
Did you check the key paths?

I did some tests, and compared to other wallets, but could not find any problems.

**Comment by iteh3712198** [comment]
> Did you check the key paths?
> 
> I did some tests, and compared to other wallets, but could not find any problems.

I exported the WIF private key from the unisat wallet and then used the following code to get the taproot address, can you help me see where I might be going wrong?
```
from bitcoinlib.keys import *
 key = Key(wif_key)
 addr = Address(hashed_data=key.hash160, script_type='p2tr', encoding='bech32').address
```

**Comment by mccwdev** [comment]
I think taproot uses the public key instead of the hashed public key for the address.

Can you try it like this:

```python
from bitcoinlib.keys import *
key = Key(wif_key)
addr = Address(hashed_data=key.public_hash, script_type='p2tr', encoding='bech32').address
```

**Comment by xll970211** [comment]
I try like this, but my key don't have public_hash function， bitcoinlib                0.6.13 @mccwdev
