### ISSUE TITLE
wallet.transactions_update() It's not working as it should.

### ISSUE THREAD

**Issue by 1337kingOf** [1200wd/bitcoinlib#354]
I have no errors, everything is working fine, but when I send money to my bitcoinlib wallet for the first time, it can see it. However, if it's the 2nd or 3rd transaction, it just doesn't see it immediately, and only after some time (like 10 min +) and many calls to wallet.transactions_update() might it eventually see the transaction. How can I change the provider or add my own API key, for example, for Blockchair?

**Comment by 1337kingOf** [comment]
<img width="1380" alt="Screenshot 2023-12-03 at 3 46 38 PM" src="https://github.com/1200wd/bitcoinlib/assets/110034904/031802ac-b722-453d-9e14-c0cbdfa0e19f">
<img width="716" alt="Screenshot 2023-12-03 at 3 47 24 PM" src="https://github.com/1200wd/bitcoinlib/assets/110034904/4d055a65-b989-454b-85cf-02f2860a282f">
Its dont see last transaction, im checking like 24 mins and still didnt get this transaction

**Comment by 1337kingOf** [comment]
is there way to do like wallet.update_from("Provider","api")

**Comment by mccwdev** [comment]
> is there way to do like wallet.update_from("Provider","api")

Yes you can change the Wallet.providers attribute:

```python
wallet.providers = ['blockcypher', 'more-providers', ...]
```

**Comment by mccwdev** [comment]
Could it be that is only shows up after is was confirmed?

I've noticed before that some providers do not return unconfirmed transactions.

Maybe you can check in bitcoinlib.log, if you can see which provider returns incorrect results. I will run some tests myself as well.

**Comment by OculusVisionSellix** [comment]
have some problem ._.

Using PostgreSQL server.

Litecoin, more than 10+ confirmations still money doesnt show up in my balance.

**Comment by OculusVisionSellix** [comment]
It seems I had the wrong address, when I receive money on the address which is displayed by:
account.as_dict()["address"] the program doesnt recognize the balance
I used the wallet.addresslist(account_id=account.account_id) address and it worked
