### ISSUE TITLE
Using BIP38 encrypted Private Key throw error

### ISSUE THREAD

**Issue by alex-frx** [1200wd/bitcoinlib#362]
When using a BIP38 encrypted Private Key I get an: `EncodingError: Unrecognised password protected key format. Flagbyte incorrect.` Error 

Minimal example: 

```
from bitcoinlib.keys import Address,Key

public_address = "1CTHRG6Te7dvbb5RQ6JuDv6tNdMH6Fahic"
private_key = "6PnV1MS7UY4wjdAGucW2MdTuDNiTvQPthTjiMex6HNv2NfLXLk8CKQfCnL"
password = "hallohallo"

key = Key(private_key, password=password)
print(key.info())
```

The pair were generated using [bitaddress.org](https://www.bitaddress.org/bitaddress.org-v3.3.0-SHA256-dec17c07685e1870960903d8f58090475b25af946fe95a734f88408cef4aa194.html)

or am I using it wrong

**Comment by mccwdev** [comment]
EC multiplied BIP38 addresses are not supported at the moment.
For now I made commit https://github.com/1200wd/bitcoinlib/commit/fe5f9b60d694cda59ab51544164cc329e2dbdd52 to raise a more informative error.
