### ISSUE TITLE
Possibility to generate addresses that all link back to one private key?

### ISSUE THREAD

**Issue by Endogen** [1200wd/bitcoinlib#40]
I know that this works of course but is it possible with you're library? And if yes, how would i go about that if i wanted to implement it?

Again, the idea is, that i generate a new address everytime i want to receive coins but still have the initial mnemonic 12 words to access the funds.

**Comment by mccwdev** [comment]
Yes the library uses Hierarchical Deterministic keys. So with one masterkey you can create an infinite number of derived keys.

You can find some examples on https://bitcoinlib.readthedocs.io

**Comment by Endogen** [comment]
Ok, the way i understand it is, you have one master key (Extended Private Key) that can recreate the private key for every address that belongs to the wallet with the master key.

But is it somehow possible to have all funds on one address and still change the address you give out to people if they want to pay you? So every time i receive a payment i give out a different address but in the end, all funds are in the same address?

I guess they are not in the same address then but in the same wallet but then the questions is, can i access all funds in that wallet without having to for example withdraw from every address within this wallet? Can i just withdraw once and get all coins in every address that is part of that wallet?

I hope it's kind of understandable what i want to achieve

**Comment by Endogen** [comment]
I understand the concept now. Thanks for the initial help!

**Comment by mccwdev** [comment]
Great! Just a little remark: You can indeed create a single transaction to withdraw all funds on every address (spend the unspent outputs). The only consideration could be one of privacy, because with this transaction everyone can see all the addresses belong to the same entity.

**Comment by Endogen** [comment]
An example for that would be really nice :-) Maybe you can give me some hints how to do that?

**Comment by mccwdev** [comment]
You can use the sweep method for that, see https://github.com/1200wd/bitcoinlib#multi-signature-wallets for example
