### ISSUE TITLE
Obtain transaction hash when generating raw transaction with several utxo inputs and outputs

### ISSUE THREAD

**Issue by Menetar** [1200wd/bitcoinlib#41]
Hi!
I was wondering, when I sign a transaction with just one input, I receive the transaction has without problems. Yet, when i send an array of inputs and outputs, the answer from the : 
- t = Transaction(inputs=inputs,outputs=outputs, network=network_id)
- t.sign(pubkey.private_byte)
- sendrawtransaction(t.raw_hex())
It returns a 'FALSE' rather than the tx hash itself.
bitcoinlib version: 0.3.33a2

Thank you for yout time!

**Comment by mccwdev** [comment]
In this version the sendrawtransaction method returns the transaction hash only if it pushed the transaction successfully. So if False is returned it means the transaction is invalid or it could not be pushed to the network.

You can check if t.verify() returns True and with t.info() if you can maybe find something incorrect in the transaction. If that doesn't help check the logs to see if there are any problems with the service providers.

**Comment by Menetar** [comment]
Hi!
t.verify does return True. The funny thing is, the transaction actually goes to the blockchain so it is valid and all, but it still returns False. Let me check t.info() to see what it's content is.
Thanks!

**Comment by mccwdev** [comment]
This sounds like a familiar bug, updating to the latest version should fix this
