### ISSUE TITLE
Can't access sqlite in different thread

### ISSUE THREAD

**Issue by Endogen** [1200wd/bitcoinlib#42]
I'm accessing some data in a wallet thru a thread that is not the same as the one that created that wallet. Thus i get this error:

```
'(sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140736073909120 and this is thread id 123145438023680'
```

Is it possible to create the db with `check_same_thread=False`?
```
conn = sqlite3.connect('your.db', check_same_thread=False)
```

I know you use SQLAlchemy and there it should be set a mentioned [here](https://stackoverflow.com/questions/33055039/using-sqlalchemy-scoped-session-in-theading-thread)

Any chance you could add that as an option?  BTW: Your lib is awesome! Like it very much :-) It's even a bit over the top for my usecase but still absolutely great.

**Comment by mccwdev** [comment]
Thank you!
I will do some experiments but I'm not sure if SQLite supports multiple threads, and if it could cause other problems.
Do you mind sharing the code causing the sqlite3.ProgrammingError?

**Comment by Endogen** [comment]
SQLite supports multiple threads. Works good! I already did a small change to your code to get that working since i need that. And i think it could cause other issues but that's something that the user has to take care of if he decides to use this option.

I have nothing against sharing my code but i'm writing a Telegram bot so i would have to reduce the current code to some simple test case first. Will do that if i have the time. The [library i'm using](https://python-telegram-bot.org) is multithreaded - so i need that change. Otherwise your lib will not work with the bot lib...

The change i've made is in line 47 of `db.py`
```python
self.engine = create_engine('sqlite:///%s' % databasefile, connect_args={'check_same_thread': False})
```

Sorry i don't have the time for a PR right now

**Comment by mccwdev** [comment]
Ah nice project a Telegram bot with Bitcoin, looking forward to see a test case.
In the mean time I will read some SQLalchemy docs and test your changes, to see if it works.

**Comment by famecastle** [comment]
I added the Pull Request #107 regarding this.
