### ISSUE TITLE
Do not override sys.excepthook as it affects any app globally where this library is used

### ISSUE THREAD

**Issue by darklow** [1200wd/bitcoinlib#423]
As soon as any module of function from this library is imported, following line affects exception handler in whole app, not just library, making it hard to develop and see exact traceback. Consider some less global option to silent tracebacks within library only. Thank you.
https://github.com/1200wd/bitcoinlib/blob/685f097b56d458155af9c246679a5556b545b7ab/bitcoinlib/tools/clw.py#L33

**Comment by mccwdev** [comment]
Fixed in commit c16b555
