### ISSUE TITLE
How to access already created HDWallet in database?

### ISSUE THREAD

**Issue by Endogen** [1200wd/bitcoinlib#43]
Sorry for the stupid question but i don't seem to understand how to access a wallet if i don't want to recreate the database file all the time. Right now i'm doing something like this:

```python
wallet_delete_if_exists(wallet_name, databasefile=db_file, force=True)
wallet = HDWallet.create(wallet_name, key=passphrase, network=network, databasefile=db_file)
```

But if the database already exists and i just want to access a wallet that i previously created, how to do that? I saw in the code that the only two methods that return me a `HDWallet` object are `create()` and `create_multisig()`?

**Comment by mccwdev** [comment]
You could use:
 wallet_create_or_open(wallet_name, key=passphrase, network=network, databasefile=db_file)

**Comment by Endogen** [comment]
Ahh, nice! Thanks for that :)
