### ISSUE TITLE
Possible to create as many addresses as i want?

### ISSUE THREAD

**Issue by Endogen** [1200wd/bitcoinlib#44]
I should be able to basically generate as many addresses for a deterministic wallet as i want but since your `account_id` is an integer, doesn't that restrict my possibilities to only 65535 addresses?

I could use account `name` without specifying the `account_id` i suppose but then by using `wallet.get_key()` i can only use an `account_id`. Also for scanning a specific address i can only use the `account_id` - or do i get it wrong?

**Comment by mccwdev** [comment]
Integers in Python are not restricted, the account_id is 4 bytes, so 256 ^ 4 accounts.

I think it better to use the account_id and not the name. A name should not be accepted by any method, is there any method which still does this?

**Comment by Endogen** [comment]
This method still uses `name`: `HDWallet.new_account()

For the second issue - i get this error if i use an `account_id` with 9 digits:
```
(sqlite3.IntegrityError) CHECK constraint failed: constraint_script_types_allowed
```

This is the code:

```python
from bitcoinlib.wallets import HDWallet, wallet_delete_if_exists

passphrase = "weird jazz filter tonight invest adjust silk soccer depart learn exile bomb"
db_file = "crypto.db"
wallet_name = "MyWallet"
network = "testnet"

try:
    wallet_delete_if_exists(wallet_name, databasefile=db_file, force=True)
    wallet = HDWallet.create(wallet_name, key=passphrase, network=network, databasefile=db_file)

    wallet.new_account(account_id=134166731, network=network)
    wallet.get_key(account_id=134166731)
    wallet.scan(account_id=134166731)
    wallet.info()
except Exception as ex:
    template = "An exception of type {0} occurred. Arguments:\n{1!r}"
    message = template.format(type(ex).__name__, ex.args)
    print(message)
```

If i change the `account_id` to let's say 3 digits, it's working fine

**Comment by Endogen** [comment]
The reason for the error is actually `wallet.scan(account_id=134166731)`

**Comment by mccwdev** [comment]
Could not reproduce this error with the same code. Are you using the latest bitcoinlib version?
Another problem could be an old database file.

**Comment by Endogen** [comment]
Yeah i'm using the current version, not installed from `pip` but direct download from GitHub. Could it be the SQLite version? I'm using Python 3.6.2 and SQLAlchemy 1.2.5

Currently for testing i create the database new every time

**Comment by Endogen** [comment]
Tested a little bit:
1) Happens with newest version installed via `pip` and also with latest master branch version
2) Happens also with completely new created database
3) It's the same on command line and Pycharm
4) With and without my change to the db (`connect_args={'check_same_thread': False}`)
5) I'm on Mac 10.13.5

**Comment by Endogen** [comment]
I looked at this a bit deeper and found that the error is thrown at line 702 in `wallets.py`. The first time the code gets called fine but the second time this code gets called in the same run will result in this error:

```python
(sqlite3.IntegrityError) CHECK constraint failed: constraint_script_types_allowed [SQL: 'INSERT INTO transaction_inputs (transaction_id, index_n, key_id, prev_hash, output_n, script, script_type, sequence, value, double_spend) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (2, 0, None, 'fb93fd8a382b9089666612f11a6ace1b12ac1051eb9088b57bfde28cc845482f', 31, '160014fd23ca9ad0a19dcdaebea2ad984c7241285005e6', 'unknown', None, 5000000000, 0)] (Background on this error at: http://sqlalche.me/e/gkpj)
```

This seems to be a database-driver issue? The URL (http://sqlalche.me/e/gkpj) tells me:

> This error is a DBAPI Error and originates from the database driver (DBAPI), not SQLAlchemy itself.

Is there anything you could add to that? I will try to run this code example on windows and see if it is still there but i kind of don't get it. Database driver means it's depending on the Python version since sqlite3 is part of standard Python, right?

**Comment by Endogen** [comment]
It's getting weird now: Tested on a system that never had `bitcoinlib` installed (with Windows 7, Python 3.6, bitcoinlib 0.3.36) and got the same error and only with this one value! So i can completely dismiss the idea that there are some old values somewhere and that they causing this.

But what doesn't make sense now is that you can't reproduce it. Do you have the possibility to test on another system?

Sorry for all this stuff but this is an issue for me and i don't have any idea how to solve this.

**Comment by mccwdev** [comment]
The error doesn't seem to be related to the database. For some reason the script type could not be determined. So the script type value is 'unknown', which is not is the list of allowed script types and therefore can not be added to the database.

Now I have to find out why the script type could not be determined and why there are different results or different systems. Normally using Linux, but I will perform some test on Windows.

**Comment by mccwdev** [comment]
On my Windows system it is working as well. Could you send the error logs from .bitcoinlib/logs/bitcoinlib.log? Maybe there is some more information there.

**Comment by Endogen** [comment]
Sure. And thanks for looking into that!

[bitcoinlib.log](https://github.com/1200wd/bitcoinlib/files/2161020/bitcoinlib.log)

I just executed the provided code once to get this log

**Comment by mccwdev** [comment]
This should fix it: https://github.com/1200wd/bitcoinlib/tree/fix-unrecognized-tx-inputs-outputs
The problem probably occurred when you try to import transaction in a wallet which are generated with another wallet. Bitcoinlib doesn't recognize the script and then refuses to import. This is just a small update which allows you to import transactions with unknown script types.

**Comment by Endogen** [comment]
Fixed it! Thanks for that :-D
