### ISSUE TITLE
How to use other RDBMS instead of sqllite?

### ISSUE THREAD

**Issue by karthik-ir** [1200wd/bitcoinlib#49]
When I create a session and pass it on, many pieces of code takes in databasefile as default entry and processes it considering it is a local sqllite. 
Instead I would like to use postgres. 

Is the code already ready to be handled this way? or is it an implementation pending?

**Comment by Moliholy** [comment]
I added https://github.com/1200wd/bitcoinlib/pull/97 with support for PostgreSQL, and potentially others like MySQL.
