### ISSUE TITLE
bitcoinlib.wallets.WalletError: Fee of 773 is lower then minimal network fee of 1000

### ISSUE THREAD

**Issue by slush0** [1200wd/bitcoinlib#56]
Hi,

while using 'litecoind' service provider, wallet.transaction_create() proposed transaction with fee bellow "fee_min" defined in networks.json and sending of transaction failed.

Code triggering the error (as you see, I don't touch fee estimation in any way):
```
lock_script = b'\x6a' + varstr(data)
t_output = Output(0, lock_script=lock_script)
tx = wallet.send([t_output])
```

**Comment by slush0** [comment]
After finding on internetz, it looks like minimum fee on LTC is 1000 sat per kB, but in https://github.com/1200wd/bitcoinlib/blob/master/bitcoinlib/wallets.py#L2762 there's comparsion of fee_min with absolute transaction fee.

**Comment by mccwdev** [comment]
Yes indeed, looks like a mix-up of fee per kilobyte and total transaction fee in the transaction_create() method. I think both are available in this method so it should be easy to fix. Not sure why I didn't notice this earlier...

**Comment by mccwdev** [comment]
Fixed in https://github.com/1200wd/bitcoinlib/tree/fix-fee-mixups.
Fee estimation needs some more work to make it more precise and include segwit, but for now it seems to work.
