### ISSUE TITLE
Can't pip install bitcoinlib on Windows 10 with Python 3.7

### ISSUE THREAD

**Issue by jamesyoungdigital** [1200wd/bitcoinlib#58]
It seems to be a problem finding headers for OpenSSL.  It can't build scrypt. and so I can't install.

crypto_aes.c
    scrypt-1.2.1/libcperciva/crypto/crypto_aes.c(6): fatal error C1083: Cannot open include file: 'openssl/aes.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "d:\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\james\\AppData\\Local\\Temp\\pip-install-tynzm0l6\\scrypt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\james\AppData\Local\Temp\pip-record-jgitvogd\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\james\AppData\Local\Temp\pip-install-tynzm0l6\scrypt\
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Does anyone know how to resolve the scrypt package failed to build issue to get bitcoinlib installed?

**Comment by mccwdev** [comment]
What could help is installing scrypt first with pip install scrypt and then bitcoinlib.

Also the library isn't tested yet with python 3.7, so for now it's better to use python 3.6.

**Comment by mccwdev** [comment]
Any succes yet?  The latest bitcoinlib version 4.2 is tested with Python 3.7 so this shouldn't cause any problems.  The scrypt package also requires the development version of Python, I'm not sure if this version is installed by default in your Windows / Visual Studio environment.

**Comment by jamesyoungdigital** [comment]
No success, I need a way to point it to the correct location of openssl/aes.h I think.  Is that what the issue seems to be?

Thank you

**Comment by mccwdev** [comment]
It seems there are no binary wheels for the scrypt package for Python 3.7, see https://pypi.org/project/scrypt/. So it tries to compile them and then fails. I'm not sure why it fails and how to solve it. Another thing you could try is to install the openSSL library.

**Comment by x-falcon** [comment]
@mccwdev suggest  use pyscrypt instead of scrypt

**Comment by mccwdev** [comment]
In the new version 0.4.4 support for pyscrypt is added, if installation of scrypt fails.  Pyscrypt is slow but this is not a problem if you're not using BIP38 password protected private keys.

Just install bitcoinlib and if you run into scrypt errors try 'pip install pyscrypt'

**Comment by cocoonkid** [comment]
I had the same issue with macos.

https://stackoverflow.com/questions/54617308/pip-install-produces-the-following-error-on-mac-error-command-gcc-failed-wit

I solved it with setting the export flags one time. Then I was able to pip install scrypt and everything worked thereafter.
