### ISSUE TITLE
Failing to open existing wallet with 0.4.2

### ISSUE THREAD

**Issue by slush0** [1200wd/bitcoinlib#62]
Hi,

I just updated bitcoinlib to latest 0.4.2, but the code which worked with prior bitcoinlib version suddenly throws "sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: wallets.multisig" after calling  HDWallet() constructor.

Note that I'm not using multisig wallet.

Is there any backward incompatibility and do I need to upgrade my database or is this a bug? I was unable to find anything related in README.

**Comment by mccwdev** [comment]
Hi,
Yes some fields in the database where added/changed, to update the database use the updatedb.py script in the root dir.
I will add some instructions in the README and/or try to automate the update in someway.

**Comment by mccwdev** [comment]
Please use the latest master branch when updating the database. I fixed some issues with a constrained error on the Wallet's scheme field.

**Comment by mccwdev** [comment]
Were you able to fix the issue and update the database with the updatedb.py script?

**Comment by mccwdev** [comment]
Working on database update scripts
