### ISSUE TITLE
 WARNING _provider_execute(169) No successfull response from any serviceprovider: ['bitcoind.testnet']

### ISSUE THREAD

**Issue by ezangeneh** [1200wd/bitcoinlib#76]
This is my provider config in provider.json file
```
  "bitcoind.testnet": {
    "provider": "bitcoind",
    "network": "testnet",
    "client_class": "BitcoindClient",
    "provider_coin_id": "",
    "url": "http://root:xxxxxxxx@localhost:18332",
    "api_key": "",
    "priority": 11,
    "denominator": 100000000,
    "network_overrides": null
  }
```

But service provider don't work. and don't show the balance of address

```
srv = Service(network="testnet", providers="bitcoind")
print(srv.getbalance("n3UKaXBRDhTVpkvgRH7eARZFsYE989bHjw"))
```

**Comment by mccwdev** [comment]
The config file looks correct. Could you check for a more detailed error in the logfile? Located in your userdir in .bitcoinlib/log/bitcoinlib.log.

**Comment by ezangeneh** [comment]
log file show this warning 
WARNING _provider_execute(169) No successfull response from any serviceprovider: ['bitcoind.testnet']

**Comment by mccwdev** [comment]
But somewhere above that line should be an error why bitcoind failed.
Otherwise the error could be shown with:
`print(srv.errors)`
