### ISSUE TITLE
Retrieving the UTXO's from bitcoind Full Node

### ISSUE THREAD

**Issue by mekool** [1200wd/bitcoinlib#82]
I have a Bitcoin Core full node up and running (bitcoind daemon).
I have connected bitcoinlib via RPC to this bitcoin node. The communication works fine, however, when I want to update the UTXO's from the node with these 2 lines:

wallet = wallet_create_or_open(myWallet)
wallet.utxos_update()

...bitcoinlib gives a WARNING as follows:

2019/06/03 16:41:55 WARNING _provider_execute(155) bitcoind.getutxos((['1N4r1uDSAHpeM1sTEx6AvMB43q1guh1GuW'],)) Error 'ismine'

Is it not possible to retrieve the UTXO's from bitcoind for the bitcoinlib wallet?

**Comment by mccwdev** [comment]
The service object was using a deprecated bitcoind method. This issue is fixed in https://github.com/1200wd/bitcoinlib/commit/5d32942616ebdf37490e7607e57d64c2550319a0

Thanks for your bug report!

**Comment by mekool** [comment]
Thank you.
I changed those 2 lines in the code of:
/root/venv/lib/python3.6/site-packages/bitcoinlib/services/bitcoind.py

What is next? Do I need to re-compile / re-install bitcoinlib so that the changes take effect ?
Sorry for asking this unprofessional question.

**Comment by mccwdev** [comment]
That could work depending on your installation but normally you would just upgrade/reinstall the library with something like:
`pip install bitcoinlib --upgrade`

See https://bitcoinlib.readthedocs.io/en/latest/_static/manuals.install.html

Or did you use another way to install the library?

**Comment by mekool** [comment]
Super, that worked! The library is updated and the changes have taken effect.

So now bitcoinlib is trying to retrieve the UTXO's from the bitcoind daemon for a given address of the bitcoinlib wallet, e.g. for 1FMtJUJL6Lbr6hYXoaRBdPSvsGVMuXgYKs

Then I get this WARNING:
2019/06/04 08:04:45 WARNING __init__(37) Address 1FMtJUJL6Lbr6hYXoaRBdPSvsGVMuXgYKs not found in bitcoind wallet, use 'importaddress' to add address to wallet.

It is obvious that this address of the bitcoinlib wallet is NOT contained in the bitcoind wallet, explaining the WARNING.

Is it not possible to retrieve the UTXO's for an address contained in the *bitcoinlib* wallet?

**Comment by mccwdev** [comment]
The bitcoind deamon only has information about his own addresses so or you the same private key in bitcoinlib and bitcoind (which doesn't make it any more secure) or you could import an address in bitcoind (which takes a lot of time because you need to reindex) or find another clever solution maybe.

But if you want to keep it simple my advice would be to use one of the other online service providers instead of bitcoind which are also included in bitcoinlib.

**Comment by mekool** [comment]
Hmm, I understand.
I am running a Bitcoin full node on a Linux server, and I was hoping that I could do everything via the bitcoind daemon on this server without the need to access any 3rd-party online service providers (as your approach via bitcoinlib suggests).

I like your bitcoinlib library very much. It is very comprehensive (also good documentation with practical examples) and has a very clean abstraction level to basically do everything I want with just a few **simple** programming lines.

Well anyway, I will need to move on and find another approach to utilize bitcoind's wallet.

**Comment by mccwdev** [comment]
Thanks, and good luck!
You could also look in alternative bitcoin nodes such as bitcore or bitcoin knots (see https://coin.dance/nodes), I'm not sure if bitcoind will do the trick for you.

**Comment by mekool** [comment]
I think I will simply do everything with the **bitcoin-cli** command-line interface and RPC. That should work.
