### ISSUE TITLE
Failed installation on Manjaro with Python3.7 virtualenv

### ISSUE THREAD

**Issue by brunof17** [1200wd/bitcoinlib#84]
> Collecting bitcoinlib
>   Using cached https://files.pythonhosted.org/packages/6b/34/8761684d6a146c4ce1a979383456de42e2c511f185e61655beba20c304ee/bitcoinlib-0.4.8.tar.gz
>     ERROR: Complete output from command python setup.py egg_info:
>     ERROR: Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-vlblzvx6/bitcoinlib/setup.py", line 27, in <module>
>         version_file = open(os.path.join(here, 'bitcoinlib/config/VERSION'))
>       File "/usr/lib/python3.7/codecs.py", line 898, in open
>         file = builtins.open(filename, mode, buffering)
>     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-vlblzvx6/bitcoinlib/bitcoinlib/config/VERSION'
>     ----------------------------------------
> ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-vlblzvx6/bitcoinlib/
> 

I've looked for solutions for the problem, but it seems like there is some files missing? Or wrong acess to files in 
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-vlblzvx6/bitcoinlib/bitcoinlib/config/VERSION'
>
 As it should be '/tmp/pip-install-vlblzvx6/bitcoinlib/config/VERSION'  maybe
Thanks

**Comment by mccwdev** [comment]
I got the same error with pip and will look into it. 
Thanks for your report!

**Comment by mccwdev** [comment]
Released a new version 0.4.9 which should fix this bug. The install path seems different in pip sometimes, a hard-coded version number fixed it.

**Comment by brunof17** [comment]
Thanks, it worked now.

**Comment by brunof17** [comment]
I don't know if the fix you did broke the module. When importing the module the following error occurs:

> >>> import bitcoinlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bruno/Projetos/testesBIT/lib/python3.7/site-packages/bitcoinlib/__init__.py", line 20, in <module>
    import bitcoinlib.encoding
  File "/home/bruno/Projetos/testesBIT/lib/python3.7/site-packages/bitcoinlib/encoding.py", line 28, in <module>
    from bitcoinlib.main import *
  File "/home/bruno/Projetos/testesBIT/lib/python3.7/site-packages/bitcoinlib/main.py", line 25, in <module>
    from bitcoinlib.config.opcodes import *
  File "/home/bruno/Projetos/testesBIT/lib/python3.7/site-packages/bitcoinlib/config/__init__.py", line 20, in <module>
    import bitcoinlib.config.config
  File "/home/bruno/Projetos/testesBIT/lib/python3.7/site-packages/bitcoinlib/config/config.py", line 270, in <module>
    version_file = open(os.path.join(BCL_INSTALL_DIR, 'config/VERSION'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/bruno/Projetos/testesBIT/lib/python3.7/site-packages/bitcoinlib/config/VERSION'


Do you want me to open another issue?

**Comment by mccwdev** [comment]
mmm embarrassing, the update broke the module.
I will into it again, and also think of a way to test pip installation.

**Comment by mccwdev** [comment]
It should be fixed now in a new release 0.4.10

**Comment by brunof17** [comment]
Thanks, it all works now :smiley:
