### ISSUE TITLE
Transaction hash is not calulated correctly

### ISSUE THREAD

**Issue by roth-a** [1200wd/bitcoinlib#88]
funding_tx.as_dict()  gives
`{'hash': 'd21633ba23f70118185227be58a63527675641ad37967e2aa461559f577aec43',
 'date': None,
 'network': 'testnet',
 'coinbase': False,
 'flag': None,
 'confirmations': None,
 'block_height': None,
 'block_hash': None,
 'fee': 500,
 'fee_per_kb': 1765,
 'inputs': [{'index_n': 0,
   'prev_hash': 'a927d1cba28c55f11bd50f78468467df6ccd647d6610f3100552532bc23041e3',
   'output_n': 1,
   'script_type': 'sig_pubkey',
   'address': 'muS6eoWGB8Spau89MFairAD9whFmmiPR1H',
   'value': 14715532,
   'public_keys': '04eb2c10309cf363bacef1d791c136e258dfda6a60c8cbbad0443622e7479b135ab198807e9728901f1d1da3bf46c4f2bfefd74c4ab6074baece8bc196ffc75f9e',
   'compressed': False,
   'encoding': 'base58',
   'double_spend': False,
   'script': '473044022004d3960f9a6bd1b6b54ce431197f4d8f74d0e3fc1b82ab7c8f3142521c7304b3022019bdbb56fe8e6700099d875e42278e216e1c86a1538e12607ccf38eeed708740014104eb2c10309cf363bacef1d791c136e258dfda6a60c8cbbad0443622e7479b135ab198807e9728901f1d1da3bf46c4f2bfefd74c4ab6074baece8bc196ffc75f9e',
   'redeemscript': '',
   'sequence': 13,
   'signatures': ['04d3960f9a6bd1b6b54ce431197f4d8f74d0e3fc1b82ab7c8f3142521c7304b319bdbb56fe8e6700099d875e42278e216e1c86a1538e12607ccf38eeed708740'],
   'sigs_required': 1,
   'locktime_cltv': None,
   'locktime_csv': None,
   'public_hash': '98a6a868cfee80c890eab4fac98cd502c0e1fcc7',
   'script_code': '76a91498a6a868cfee80c890eab4fac98cd502c0e1fcc788ac',
   'unlocking_script': '473044022004d3960f9a6bd1b6b54ce431197f4d8f74d0e3fc1b82ab7c8f3142521c7304b3022019bdbb56fe8e6700099d875e42278e216e1c86a1538e12607ccf38eeed708740014104eb2c10309cf363bacef1d791c136e258dfda6a60c8cbbad0443622e7479b135ab198807e9728901f1d1da3bf46c4f2bfefd74c4ab6074baece8bc196ffc75f9e',
   'unlocking_script_unsigned': '76a91498a6a868cfee80c890eab4fac98cd502c0e1fcc788ac',
   'witness_type': 'legacy',
   'witness': '3044022004d3960f9a6bd1b6b54ce431197f4d8f74d0e3fc1b82ab7c8f3142521c7304b3022019bdbb56fe8e6700099d875e42278e216e1c86a1538e12607ccf38eeed7087400104eb2c10309cf363bacef1d791c136e258dfda6a60c8cbbad0443622e7479b135ab198807e9728901f1d1da3bf46c4f2bfefd74c4ab6074baece8bc196ffc75f9e',
   'sort': True,
   'valid': True}],
 'outputs': [{'value': 10000,
   'script': 'a9141a6fe71cb937e2690dd678603b886471aa97291387',
   'script_type': 'p2sh',
   'public_key': '',
   'public_hash': '1a6fe71cb937e2690dd678603b886471aa972913',
   'address': '2Muf1cQv5VXn94mCyb9N6d6KUT4Z92m5eFk',
   'output_n': 0,
   'spent': False},
  {'value': 14705032,
   'script': '76a91498a6a868cfee80c890eab4fac98cd502c0e1fcc788ac',
   'script_type': 'p2pkh',
   'public_key': '',
   'public_hash': '98a6a868cfee80c890eab4fac98cd502c0e1fcc7',
   'address': 'muS6eoWGB8Spau89MFairAD9whFmmiPR1H',
   'output_n': 1,
   'spent': False}],
 'input_total': 14715532,
 'output_total': 14715032,
 'version': 2,
 'locktime': 0,
 'raw': '0200000001e34130c22b53520510f310667d64cd6cdf678446780fd51bf1558ca2cbd127a9010000008a473044022004d3960f9a6bd1b6b54ce431197f4d8f74d0e3fc1b82ab7c8f3142521c7304b3022019bdbb56fe8e6700099d875e42278e216e1c86a1538e12607ccf38eeed708740014104eb2c10309cf363bacef1d791c136e258dfda6a60c8cbbad0443622e7479b135ab198807e9728901f1d1da3bf46c4f2bfefd74c4ab6074baece8bc196ffc75f9e0d00000002102700000000000017a9141a6fe71cb937e2690dd678603b886471aa972913878861e000000000001976a91498a6a868cfee80c890eab4fac98cd502c0e1fcc788ac00000000',
 'size': 255,
 'verified': True,
 'status': 'new'}
`

However the ID of the transaction is "14367de4ff7285eb26905eabc711cca1cb44268d38b07114cb74bd74f59579fe"
see here:  https://tbtc.bitaps.com/raw/transaction/14367de4ff7285eb26905eabc711cca1cb44268d38b07114cb74bd74f59579fe

How can this id be calculated from
funding_tx.as_dict()['hash'] = 'd21633ba23f70118185227be58a63527675641ad37967e2aa461559f577aec43',

**Comment by roth-a** [comment]
I found a [solution](https://bitcoin.stackexchange.com/a/76197) but not with bitcoinlib tools.  Can this code be incorporated in bitcoinlib?

**Comment by mccwdev** [comment]
The transaction hash is calculated with double SHA256 hashing in bitcoinlib as it should.
Are you using only bitcoinlib to create and sign the transaction?

**Comment by mccwdev** [comment]
I'm not sure how this could occur, only if you delete the signatures and sign the transaction again maybe. But I will run some tests and see if there is an issue with bitcoinlib or one of the service providers it connects to.

**Comment by quantumfiber** [comment]
Thanks.  I was really confused too.   I didn't delete any signatures, though.

**Comment by roth-a** [comment]
Thanks.  I was really confused too.   I didn't delete any signatures, though.

**Comment by mccwdev** [comment]
Transaction hash has was not always updated when creating or signing transaction.
Fixed in https://github.com/1200wd/bitcoinlib/commit/ad412d30dd6059da3ff65d8867a7893ffb018609
