### ISSUE TITLE
2019/09/10 21:36:10 WARNING <module>(39) Could not include fastecdsa library, using slower ecdsa instead

### ISSUE THREAD

**Issue by tycooperaow** [1200wd/bitcoinlib#89]
On creation of a new wallet:
`w = HDWallet.create('Wallet1')`
I received this error from the module. 
2019/09/10 21:36:10 WARNING <module>(39) Could not include fastecdsa library, using slower ecdsa instead. 
Any clue as to what it means and what I can do to fix it?

**Comment by mccwdev** [comment]
You can try to install the fastecdsa library seperately and see if that works or if any error pops up.  
But you can ignore this warning if you are not using BIP38 encrypted keys, the speed of the library is not affected.
What OS are you using? Because I know fastecdsa and Windows is problematic.

**Comment by Goro2030** [comment]
Same here, using Windows.

**Comment by mccwdev** [comment]
For some tricks on how to get fastecdsa working on Windows see https://github.com/AntonKueltz/fastecdsa/issues/11

**Comment by mccwdev** [comment]
See https://github.com/1200wd/bitcoinlib/discussions/306
