### ISSUE TITLE
WARNING from gettransactions(txid)

### ISSUE THREAD

**Issue by Goro2030** [1200wd/bitcoinlib#92]
I'm getting a lot of warnings like this:

`2019/10/02 17:07:24 WARNING script_deserialize(402) Could not parse script, unrecognized script`

When accessing transactions that are relatively new in the bitcoin main blockchain.
For example when I try to deserialize this transaction:

[Blockchain.info link to transaction](https://www.blockchain.com/btc/tx/3730d96f43f0ff3474e0f3acf0557413147e363377913cef1f00d2a7cdfb721e)

I get the WARNING 4 times ( I guess once for each input , as it has 4 )

Ideas?

**Comment by mccwdev** [comment]
The warning are annoying but harmless, you can ignore them. Bitcoinlib tries to parse the script and if it fails it use another method.

But yes we have to rid of those warnings.

**Comment by Goro2030** [comment]
Thanks for replying so quickly! 

So if it fails with the default approach, it uses another and parses it ok? I need to be sure it is parsing the whole block, and the TX's in it.

Also, another question: How can I get rid of the warnings going into the stdout/terminal? It's filling my screen with those ... tried to silence it by several methods but couldn't.

**Comment by Goro2030** [comment]
Also getting this:

`2019/10/04 16:19:06 ERROR __init__(39) Could not parse witnesses in transaction. Multisig redeemscript expected`

Does this mean that the transaction is skipped ( es per the "ERROR" ), and not decoded?

**Comment by mccwdev** [comment]
A duplicate log handler has been removed in https://github.com/1200wd/bitcoinlib/commit/432b8bbc8b09b23abf42df7f821d7a0ffe95a964 which should disable logs to stdout
As for your last question: It's hard to say what is causing the error, please include a (test!) transaction so I can take a look.
