### ISSUE TITLE
TypeError: 'Signature' object is not subscriptable

### ISSUE THREAD

**Issue by shyal** [1200wd/bitcoinlib#93]
```
btc LeetWallet --sweep my_pub_address_here
```

Leads to:

```
TypeError: 'Signature' object is not subscriptable
```

**Comment by mccwdev** [comment]
Got the same issue in version 0.4.10, I will take a closer look.

**Comment by mccwdev** [comment]
Fixed in https://github.com/1200wd/bitcoinlib/commit/393384f4ff18524998f672e3a7190aa3035cdb53 in master branch
