### ISSUE TITLE
Bitcoind forces to register an address in order to be checked

### ISSUE THREAD

**Issue by Moliholy** [1200wd/bitcoinlib#94]
When using bitcoinilb's HDWallet implementation with bitcoind, I've realized that I was forced firstly register the addresses I was interested in, otherwise it'll return an error.

For the sake of completeness, here's the code:

```python
def update() -> None:
        addresses = wallet.addresslist(account_id=0)
        registered_addresses = set(map(lambda a: a['address'],
                                       bitcoind_execute('listreceivedbyaddress', params=[0, True, True])))
        addresses_to_update = filter(lambda a: a not in registered_addresses, addresses)
        for address in addresses_to_update:
            bitcoind_execute('importaddress', params=[address, '', False])
       wallet.utxos_update(account_id=0, networks=[wallet.network.name])
```

As you can see, if I wouldn't call the `importaddress` bitcoind method it wouldn't work. Furthermore, if I wouldn't call the `listreceivedbyaddress ` method I'd be calling more times than needed to my bitcoind node. Is this the expected behaviour, or am I missing something?

**Comment by Moliholy** [comment]
Good to know. Yes, I was adapting the code to my needs (and I'll later submit a PR with support for postgresql in case you want to take a look) and I happily saw there's support for bcoin 🎊 

I'll for now go on with bitcoind since it's what I have implemented so far, but I'll probably switch to bcoin soon.

Thanks a lot!

**Comment by tkeske** [comment]
Thank you for the code example @Moliholy

**Comment by guang2013** [comment]
> Yes I think this is the only way to solve it with bitcoind, as bitcoind has detailed information about own wallet transactions.
> 
> You could use another bitcoin node such as bcoin which stores information about all addresses and transactions. I've added support for bcoin in the latest master branch.

Hello, could you help to detail how to configure with bcoin, Thanks a lot.

**Comment by mccwdev** [comment]
In short: Install the bcoin server and then add the configuration string to bitcoinlibs providers.json:
```
 "bcoin": {
    "provider": "bcoin",
    "network": "bitcoin",
    "client_class": "BcoinClient",
    "provider_coin_id": "",
    "url": "https://x:password@localhost:28332/",
    "api_key": "",
    "priority": 20,
    "denominator": 100000000,
    "network_overrides": null
  },
```

I'm planning to add more detailed bcoin setup guide later.
Please let me know if you bump into any issues.
