### ISSUE TITLE
Parcial update of an HDWallet

### ISSUE THREAD

**Issue by Moliholy** [1200wd/bitcoinlib#95]
My use case is the following:

I am working for an exchange, and I am going to process in a backend service lots of orders per minute in bitcoin.

My original idea was to create a wallet per user ID so that users can send funds to their own "wallets". However I saw all methods to send/update require an `account_id` parameter, which seems to imply I cannot mix inputs from several accounts into a fat output whenever we have to collect the received money once every 1-2-3 hours. Am I correct? If so, is there something that could be done to fix it?

My second idea was to use a sole wallet (account 0) and create several addresses whenever a customer creates an order. It works fine, but when calling the `utxos_update` method it takes a very long time to update, until the point that the caller gets a request timeout with more than ~1000 generated addresses. After inspecting the code I realized this occurs because all addresses, including old ones, are again and again refreshed. I understand that my use case is pretty special and not valid for the vast majority of users, but wouldn't be a good idea to update the balances based on some criteria? Concretely, couldn't I just filter the addresses (keys) I'm interested in and update only those utxos? I know I can do that manually, but that implies SQL updates are made one by one and address queries to bitcoind are made one by one as well instead of five by five, which is pretty inefficient and slow. Could this be improved?

**Comment by mccwdev** [comment]
Nice use case!
I was running into the same kind of performance issues when using wallets with large number of addresses and utxos, so I've made a number of improvements in the 'add-new-providers' branch. You could switch to this branch if your still in development phase, it should become final in the next few weeks. With the new HDWallet.scan_key() method you can update a single address for instance. 

And it you would like to sweep a whole wallet every few hours it is best to use single account at this moment, although you could also write a sweep_multiple_accounts() method, it's more a matter of taste.

**Comment by Moliholy** [comment]
> I've made a number of improvements in the 'add-new-providers' branch.

Nice! I'm going to take a look!

> And it you would like to sweep a whole wallet every few hours it is best to use single account at this moment

I don't want to sweep it, just to leave 1-2 BTC in the wallet and collect the remaining. 

> although you could also write a sweep_multiple_accounts() method, it's more a matter of taste.

Paying more fees in transactions by sending multiple times is not a matter of taste when trying to be competitive on the wild. I of course don't pretend to discriminate what is right or not, just that the approach doesn't serve my needs as a user of the library. For instance, I might want to send at once a huge output collected out of many inputs from different accounts straight to kraken to exchange it, and Kraken only allows me to send it in a single transaction (I don't know if it's the actual case, it's just an example).

**Comment by mccwdev** [comment]
My point is that you will need to create a method which creates transactions using multiple accounts. The bitcoin library is set up to keep accounts separated and not mixed up, but still you can bypass this and create a 'send_from_multiple_accounts' method.
A maybe simpler approach is using a single wallet and use the 'owner' attribute of the key object to separate users.
