### ISSUE TITLE
Raise exceptions rather than returning False

### ISSUE THREAD

**Issue by Moliholy** [1200wd/bitcoinlib#96]
When interacting with the library I realized that if there are not enough funds the `send_to` method returns `False` rather than raising an exception (`WalletError`?) with a proper explanation of the error. In order to find the cause I have to either debug the code or inspect the logs. I think it should never return anything other than a `HDWalletTransaction` object, as it actually states in the documentation of all methods. Also, as developers we could inform the user of what happened using the exception message, rather than guessing if it's because there are not enough UTXOs or some other reason.

Still, if it's considered OK to return `False`, at least the documentation should be updated accordingly.

**Comment by mccwdev** [comment]
Good point, I think raising an exception is better indeed.

**Comment by mccwdev** [comment]
Fixed in https://github.com/1200wd/bitcoinlib/commit/47161670aa51577693ba6ed26eec1212739bb896
